---
published: true
organization_id: '2013005'
year_submitted: 2014
category: learn
body_class: blueberry
project_id: '4102004'
title: Alliance Mentoring Program (AMP)
project_summary: >-
  AMP is a one year, peer mentor college transition program to strengthen
  college matriculation and persistence of Alliance alumni.
project_image: >-
  http://maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F20500%252Fdisplay%252F2013_Graduation_Luskin_Academy_(54).jpg=c570x385
project_video: ''
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - SGV
  - SFV
  - SOUTH BAY
  - LA COUNTY
Please identify any partners or collaborators who will work with you on this project.: "In addition the Alliance the College Success Team at Alliance College-Ready Public Schools, the following Alliance high schools' college counseling programs  participate in AMP:  Alliance Dr. Olga Mohan High School, Alliance Gertz-Ressler High School, Alliance Patti & Peter Neuwirth High School, Alliance Cindy and Bill Simon Technology High School, Alliance Health Services Academy High School, Alliance Marc and Eva Stern Math Science High School, Alliance Tennenbaum Family Technology High School, Alliance Judy Ivie Burton Technology High School, Alliance Environmental Science and Technology High School, Alliance Collins Family College-Ready High School and Alliance Media Arts and Entertainment Design.  In 2014-15, Alliance College-Ready Academy High School 16 will join the program.  \r\n\r\nParticipating community colleges include East Los Angeles College, Pasadena City College, El Camino College, Santa Monica College, and Los Angeles City College. Participating four year universities include Cal State Los Angeles, Cal State Dominguez Hills, Cal State Northridge, Cal Poly Pomona, UCLA, UC Riverside, and UC Irvine.  \r\n\r\nThe colleges and universities provide vital first year services to incoming freshman, including academic preparedness resources (via tutoring services, counseling, workshops and school orientation programs) and financial hardship resources (via financial aid, financial counseling, and work study).  Additionally, several participating colleges visit Alliance high school campuses to educate and enroll incoming Alliance freshman in first year, university-based support programs and placement exams.  Others have hosted orientation days specifically for Alliance alumni and incoming Alliance freshman, including discussion of the peer mentoring program.  \r\n\r\nAlliance through its college counselors, AMP coordinators and, most importantly, AMP mentors provide the necessary social and cultural capital to leverage the resources provided by the colleges and universities.  Alliance mentors serve as extended outreach for college and university first-year completion programs.    "
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  AMP is a one year, peer mentor college transition program to strengthen
  college matriculation and persistence of Alliance alumni.
Does your project impact Los Angeles County?: 'No'
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - San Gabriel Valley
  - San Fernando Valley
  - South Bay
  - 'LA County '
What is your idea/project in more detail?: >-
  AMP provides incoming Alliance college freshman with peer mentors who are
  successful second and third year Alliance college students.  Through regular
  meetings and coaching which begin in the final semester of high school through
  the first year of college, mentors provide personal guidance and counseling to
  support the new college students' seamless transition into college, as well as
  success in that critical first year of college. AMP builds both mentor and
  mentee development by encouraging growth in the areas of leadership,
  communication, self-direction, and problem solving skills. In 2014-15, AMP
  will expand to include 700 Alliance college freshman and 100 mentors who
  attend 12 southern California colleges & universities. 
What will you do to implement this idea/project?: "Alliance begins by identifying mentors from Alliance alumni who are in their second or third year of college at one of the 12 largest feeder colleges for Alliance graduates.  Potential mentors are nominated by Alliance teachers and administrators, interviewed and rated based on their academic success, resilience, campus involvement, time management, and willingness to commit to the program for a year. As the program expands, mentor recruitment will expand to include the existing pool of mentees who have successfully moved on to their second year of college. \r\n\r\nAfter mentors are secured, mentee recruitment begins in April at 13 participating Alliance high schools. All Alliance students attending the targeted post-secondary institutions are eligible to participate and are highly encouraged to do so via an introductory program presentation that occurs during the school day at participating high school sites. Potential mentees provide personal and academic information that assists in developing the most productive mentor/mentee pairings. \r\n\r\nThe relationship between the mentor and the mentee is paramount to the success of the program. Mentees are placed in groups led by a mentor using information gathered during the recruitment process. After the group placements are completed, all AMP participants (mentors and mentees) meet at the high school site, prior to high school graduation. The purpose of these kick-off events is to enhance the bond between mentors and mentees and between mentees themselves. Mentors meet with their mentees formally four times throughout the school year to discuss specific topics related to the mentees integration into college life.  Additionally, mentors and mentees are encouraged and often meet more frequently and informally throughout the year.  \r\n\r\nMentors receive monthly professional development in a group setting to encourage collaboration and learning among mentors.  Curriculum for the mentors is research-based and includes such topics as professional communication, data tracking, time management, leadership training, and problem solving skills.  Additionally, professional development sessions include self-reflection, sharing of best practices, providing relevant feedback on AMP, and celebrating successes.  \r\n\r\nAMP mentors also work closely with the 12 colleges and universities, ensuring mentees are successfully integrated into existing university-based programs for first year and first generation college students."
How will your idea/project help make LA the best place to LEARN today? In 2050?: "On average, college graduates have healthier, more productive and civically engaged lives. College graduate are two times more likely to vote than those without a degree, will earn 66% more income over their lifetime, are 67% less likely to live in poverty, and are two times more likely to volunteer. \r\n\r\nNationally, only 8.3 percent of low-income students earn a bachelor’s degree by their mid-20s. In Los Angeles Unified School District where 77% of students live in households so poor that they qualify for the federal Free and Reduced Lunch program, the importance of increasing college going and graduation rates are important for the long-term health of the economic, civic and cultural life of Los Angeles and for all its students.  \r\n\r\nEven for those high school graduates who go to college, nearly 50% do not graduate within 5 years. Research demonstrates that the majority of college dropouts happen in the first year with more than 30% of college freshmen quitting by the end of their freshman year. For low-income, first generation college students, this first year dropout rate is even more pronounced. As striking, anywhere from 10-40% of students experience \"summer melt\", the phenomenon in which students are accepted to college, but never actually attend college.  Again, low-income and first generation students experience “summer melt” at far higher rates.   \r\n\r\nWhile Alliance students graduate high school and are accepted to college at rates significantly higher than their peers in LAUSD and the state, first year college persistence rates for our alumni mirror national trends. For each graduating class, 65% to 70% of students persist through the first year of college into the second.  \r\n\r\nIn the first two years of AMP, the \"summer melt\" rate decreased from 22% to 15% and first year persistence rates increased from 85% to 90%.   \r\n\r\n AMP provides an innovative and sustainable way to support low-income students in their transition into and through that first critical year of college, significantly increasing their likelihood of post-secondary degree attainment and as a result a healthier, more productive and civically engaged life.  \r\n\r\nAMP also offers a unique partnership model between K-12 school districts and post-secondary institutions to support the seamless and successful transition into and through the first year of college."
Whom will your project benefit?: "The immediate beneficiaries of AMP are the low-income students participating in the program -- both the incoming college freshman mentees and second and third year college peer mentors.  AMP will increase mentee first year college completion rates and increase significantly their odds of graduating from college. AMP mentors also gain valuable leadership and work-readiness skills as part of the program.  \r\n\r\nAMP will also benefit the participating colleges and universities, strengthening the first year programming and persistence rates for its students.  AMP students provide a systematic feedback and evaluation loop to inform universities about the efficacy of their first year and first generation programs.   \r\n\r\nLonger term, the beneficiaries will be the families and the communities of the AMP students.  A college education changes more than just the life of a student, it has the power to change an entire community.  Those with a college degree are more likely to be active in their neighborhoods by volunteering and voting in local elections. Most importantly, college graduates serve as role models for their families, friends and neighbors, inspiring them to follow in their footsteps.  \r\n"
How will your project impact the LA2050 “Learn” metrics?:
  - >-
    Percentage of community college students completing a certificate, degree,
    or transfer-related program in six years
  - College matriculation rates
  - >-
    Student education pipeline (an integrated network of pre-schools, K-12
    institutions, and higher education systems that prepares students for
    seamless transitions between high school, higher education institutions, and
    the workforce) (Dream Metric)
Please elaborate on how your project will impact the above metrics.: "The majority of college dropouts happen by the end of the first year of college. By stemming the dropout rates of first year college students at both community colleges and four-year universities, AMP significantly increases post-secondary degree attainment for participants in the program.   \r\n\r\nAMP also offers a seamless transition between high school and college.  Mentees first meet their mentors before they graduate from high school.  Mentors come directly from the universities and colleges that the students will attend and provide important, specific and personal support through the summer months leading up to college as well as through the first year, ensuring AMP freshman experience a seamless transition between high school and college. \r\n\r\nAMP has already shown to significantly decrease the \"summer melt\" phenomenon among incoming college freshman, thereby strengthening college matriculation rates.  \r\n"
Please explain how you will evaluate your project.: "AMP will be measured on its ability to meet the following three metrics: 1) reduce \"summer melt\" to no more than 5% of AMP participants, 2) achieve first year persistence rates of 90%, and 3) increase 6-year college graduation rates to 75% for AMP participants.  \r\n\r\nThe program will also measure lead indicators that serve as predictors of student college persistence and graduation. Indicators include the percent of students who participate in university-based first-year experience and other campus support programs, as well as student involvement with campus social and academic clubs. \r\nEvaluation will be done formally three times each year - October, February and July.  Evaluation will include analysis of mentor-mentee interactions via contact logs; surveys and focus groups of both mentors and mentees; and the academic performance of both mentors and mentees, including course load, remedial coursework, GPA, academic probation. Annual evaluation will add to that data and track the number of students that persistence into the next year,  as well as ultimate graduation rates of AMP participants.  \r\n"
What two lessons have informed your solution or project?: "While Alliance has been successful at increasing the high school graduation rates of low-income students in Los Angeles (94% grad rate) and successful in helping our students get accepted to college (95% college acceptance), we have been less successful in preparing them fully for success in college. Alliance alumni persistence rates mirror those of low-income students of color nationally. After several years of tracking our alumni, we discovered 3 important impediments to their success in college – academic preparedness, financial hardship and a social isolation when our students arrive on campus.  As a result, Alliance has adjusted several strategies, including curriculum changes that support more writing and offers more intervention and remediation while in high school so students reduce the need for remediation in college. Secondly, our counseling program has increased efforts to support students in identifying and securing financial aid.  \r\n\r\nAMP addresses the critical third hurdle which is the social and cultural isolation that low-income students experience when attending college. Research indicates that students who develop a sense of belonging and connectedness to their university are more likely to succeed.  As such, Alliance crafted AMP to include the following strategies: 1) development of peer relationships, 2) connecting students to college and university through existing campus resources and support programs, and 3) ensuring ongoing check-ins that serve an early warning system for students at risk of dropping out.    \r\n\r\nThe other important lesson has been our commitment to organizational efficacy, ability to scale, and long-term sustainability. Few organizations provide direct support to students during the college transition period – most focus on college preparedness while students are in high school OR college retention programs once students are in college. For the few that do provide transition support, the ability to scale is limited to by the cost structure. Alliance’s goal has always been to work at scale, not only for our students, but also to serve as a model for other school networks and school districts.  Staff costs are relatively low, with peer mentors serving as the frontlines of program delivery.  Peer mentors serve 3 critical functions: 1) financial sustainability & scale, 2) empowerment of peer mentors, and 3) critical peer support that is critical to the success and integration of incoming college freshman. "
Explain how implementing your project within the next twelve months is an achievable goal.: >-
  AMP is entering its third year of operations, has developed a well-thought out
  program and has demonstrated the capacity to scale the program.  Three years
  ago, the program was piloted with 34 mentees and 5 alumni mentors from one
  Alliance high school who were attending two colleges.  Year one focused on
  curriculum development, evaluating what worked and refinement for the
  following year.  Indeed it was in the year one pilot that Alliance became
  aware of the “summer melt” problem and adjusted the program so that the first
  interaction between mentee and mentors occurred while the mentee was still in
  high school as opposed to the first month of college.  In 2013-14, the program
  expanded to include 189 mentees and 12 mentors from four Alliance high schools
  who attended four local colleges and universities.  The major learning in this
  year was how to do better mentor – mentee matching.  In the 2014-15 year,
  Alliance has again expanded AMP by adding two program coordinators who serve
  520 mentees and 86 mentors from 13 Alliance high schools who attend 12
  southern California colleges and universities.  In the coming year,
  identification of new mentors for the 2015-16 school year begins in January of
  2015 and new mentees are identified in March of 2015. For 2015-16, we will
  expand to include 700 mentees and 100 mentors from 14 Alliance high schools. 
  Staffing is in place and the program is a well-organized for continued
  implementation of the 2014-15 mentee cohort as well as the recruitment of the
  2015-16 mentee and mentor cohort.  
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "One challenge includes the early buy-in of some Alliance high school seniors who will attend college the following fall. We could potentially have more students in the program than we currently do.  Our goal is to have 60% of the graduating class of all Alliance high schools in the program.  We are currently at 40%.   As high school students, they often lack understanding of what will be required of them as they transition to college and, frankly, don’t know what they don’t know in terms the help and support they will need.  Secondly, students are often reluctant to pair up with “strangers” or people they do not know well.  Thirdly, students do not want to be perceived as needing help.  To remedy this challenge, the AMP staff are working more closely with the college counselors to introduce AMP to students earlier in the year.  We are also brining in past participants in AMP to discuss the benefits of the program with Alliance high school seniors.  Finally, we are carefully crafting the program messaging as network support system for all Alliance students vs. individual coaching and support. \r\n\r\nThe other anticipated challenge will be the growing need for mentors as the program grows.  While mentors gain valuable training and leadership development experience, as low-income students themselves, they face the financial pressure and time constraints of their low-income college peers.  In the short-term, Alliance will expand the benefits of serving as a mentor to include book stipends to ease some of their financial burden.  Over the long-term, our goal is to explore with our university partners more formal certificate programs and potential course credits for serving as an AMP mentor.  \r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Publicity/awareness (social capital)
  - Education/training
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/alliance-mentoring-program-amp/maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F20500%252Fdisplay%252F2013_Graduation_Luskin_Academy_(54).jpg=c570x385.jpg
maker_image_id: '20500'
maker_image_file_name: 2013_Graduation_Luskin_Academy_(54).jpg

---
