---
published: true
organization_id: '2014005'
year_submitted: 2014
category: create
body_class: banana
project_id: '4102006'
title: 'Create LA: The Place Where No Space – or Life – is Wasted'
project_summary: >-
  ABF's project unlocks the potential of the formerly incarcerated to serve as
  caretakers of their communities in LA through urban farming.
project_image: 'https://img.youtube.com/vi/Eg3e5xfocOk/hqdefault.jpg'
project_video: 'https://www.youtube.com/embed/Eg3e5xfocOk'
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
Please identify any partners or collaborators who will work with you on this project.: "ABF has both confirmed and pending collaborators on this project.  These partner organizations include restorative justice ministries, reentry housing programs, local businesses, schools and churches. \r\n\r\nNotably, ABF’s new partnership with The Francisco Homes (TFH), a transitional housing for the formerly incarcerated, provides an opportunity for a larger impact.  The singular impact of this collaboration between ABF and TFH rests upon these three factors that ensure the success of this endeavor: 1) combination of resources, 2) complementary services for the formerly incarcerated, and 3) consolidation of support to reintegrate the formerly incarcerated into community.\r\n\r\nWhile ABF emphasizes reintegration through urban farming, and TFH places emphasis on reentry housing, both ABF and TFH work complementarily.  The work of reintegration through this collaboration mutually strengthens our respective missions and creates greater impact for those who were locked up to become productive members of our communities.   \r\n\r\nBoth ABF and TFH have supportive networks to help address both immediate and long-term needs of those recently released from prison.  Working collaboratively and sharing these supportive networks consolidates support services to ensure successful reentry while preserving public safety, and further, promoting the overall public health.  The ABF and TFH collaboration creates a larger impact by empowering those who were incarcerated to restart their lives in the setting of a new home and to reintegrate their lives into communities through urban farming.\r\n\r\nABF continues to collaborate with local businesses.  Most notably, we collaborate with local restaurant Good Girl Dinette in Highland Park by identifying and growing vegetables for seasonal specials on their menu.  \r\n\r\nABF also collaborates with schools and churches.  Most notably, ABF’s collaboration with staff and students from Cal Poly Pomona’s Department of Landscape Architecture has developed a system for chicken coop installations that will increase the variety of food produced in ABF’s urban farms.  \r\n\r\nABF’s partnerships with reentry housing programs, local restaurants and businesses, schools and churches create more opportunities to scale up the scope of support services for the reintegration of the lives of those who were locked up and the empowerment of communities where urban farming takes place. \r\n"
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  ABF's project unlocks the potential of the formerly incarcerated to serve as
  caretakers of their communities in LA through urban farming.
Does your project impact Los Angeles County?: Yes (benefits a region of LA County)
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
What is your idea/project in more detail?: "Recognizing that LA is a place where no life or space is wasted, ABF creates opportunities for the formerly incarcerated to build up the health of communities by growing healthy food in and for these communities.  \r\n\r\nThe impact of ABF with its seasoned staff proposes real solutions to the growing problems of California’s overcrowded prisons and food injustice in LA’s low-income neighborhoods.  \r\n\r\nABF aims to grow the scale of its operations by forging partnerships with existing reentry housing programs for the formerly incarcerated throughout the region of LA in order to create more urban farms for growing organic food, training and employing urban farmers, and gathering and synergizing community members around this effort.  "
What will you do to implement this idea/project?: "ABF supports the formerly incarcerated in their transition from prison isolation to community integration.  In order to successfully reintegrate, people require the chance for community, productivity and the experience of self-worth. \r\n\r\nThrough ABF, women and men have an opportunity to develop a variety of job and life skills as urban farmers.  They serve the community by growing food for families in need and for restaurants providing locally sourced and organic food.  They serve their own families through education about healthy nutrition and through developing strong work ethic and habits in an organization that prioritizes ethical business practices and excellence in the work we deliver.  \r\n\r\nThe manifestation of this idea to create an LA of reintegration through urban farming is a dynamic process of DIALOGUING, DIGGING, and DELIVERING.  This project of creating opportunities for the formerly incarcerated begins with dialogue between ABF and its partner-organizations and partner-landowners.  Mindful of the particular and distinct roles among organizations that work with and for the formerly incarcerated, ABF listens carefully to its partners’ needs.  This ensures careful planning for the creation of a sustainable urban farm.  \r\n\r\nFollowing dialogue is digging – the process of turning over soil and uncovering the potential of the land.  This project phase of digging includes designing and implementing the edible landscape and water-wise irrigation made up of raised beds for vegetables, pollinator beds with California-friendly plants, and drip irrigation systems for efficient watering.  \r\n\r\nThe third phase of project implementation is delivering harvest for two primary reasons, outreach and revenue.   A portion of the harvest from these urban farms will provide individuals and families in low-income neighborhoods with affordable and healthy seasonal food while an allotment supplies seasonal ingredients to restaurants for revenue to sustain this endeavor.  \r\n\r\nThis project of community-supported reintegration of the formerly incarcerated is a reminder that all in LA are stakeholders for making LA the best place in the world to create, learn, play, connect and be the healthiest place to live.  The interdependence of lives and landscapes in LA consolidates a collective voice that exclaims a sense of shared ownership that this is OUR LA."
How will your idea/project help make LA the best place to CREATE today? In 2050?: "With its partner-organizations, ABF will make LA the best place to create today because its collaborative urban farming project proactively engages and empowers the diversity of lives and landscapes to hold a stake in making LA the best place to create a better tomorrow.  \r\n\r\nToday’s headlines of the ever-increasing levels of incarceration and overcrowded prisons, the escalating health challenges of overweight and obese children and adults, and the proliferation of food deserts that lack ready access to fresh, healthy and affordable foods in LA’s urban neighborhoods are intertwined symptoms stemming from the devastation of human isolation.  \r\n\r\nLike preparing soil for seed sowing, ABF and its partners work to integrate the formerly incarcerated into the larger community by continually amending the attitude of the larger community through opportunities for interaction around the activity of urban farming, food delivery and nutrition education in addition to continuing advocacy efforts.  \r\n\r\nThis is a necessary step taken for preparing the larger community to extend its welcome.  ABF, along with our urban farmers and partners, will also be transforming landscapes within communities, helping to shift the relationships between residents and the spaces they inhabit.  \r\n\r\nThrough urban farming today, persons – formerly incarcerated and not – integrate into renewed spaces: backyards re-created into urban farms and drought-tolerant landscapes that welcome home birds, bees, and bugs that we all rely upon for LA’s well being.\r\n\r\nThe LA of 2050 holds promise as LA today participates actively and consciously in the process of reintegrating and welcoming home the prisoner, re-purposing backyards into urban farms and, ultimately, creating an ecology of interdependence.  \r\n\r\nAccording to James Jiler in Doing Time in the Garden, “Many of the ‘pristine’ forests in the Central American jungles are nothing more than overgrown kitchen gardens established by the Mayan Indians centuries ago.”  LA today could leave its legacy for the LA in 2050 and future generations by integrating the diversity of life and installing urban farms that will provide for LA’s fruitful future.  Reintegrating the formerly incarcerated creates greater diversity in the LA community while repurposing backyards into urban farms is the beginning to the 2050 LA food forest.   \r\n"
Whom will your project benefit?: "The complexity of interdependent relationships connected to ABF’s vision for LA speaks to some of the beneficiaries.  We anticipate the primary beneficiaries of this project will include the diverse population of the formerly incarcerated who, with the support of ABF and its partners, have a new opportunity as urban farmers to pursue their dreams of becoming productive, creative members of the community on their return home.  The urban farmers participating in ABF will bring benefits to their families and neighbors through setting alternate examples for behavior, productivity and creativity within the community.  \r\n\r\nWhile this opportunity in urban farming provides immediate job and life skills, this project gradually unlocks the potential of persons once in the custody of the criminal justice system to serve as custodians and caretakers of the communities in which they live.  The ripple effect of reintegrating those who were formerly incarcerated restores their identity as family members and community contributors.\r\n\r\nExtending benefits beyond the personal lives of the formerly incarcerated, this project has a larger and direct impact within the communities that welcome urban farming.  More specifically, there is an outreach component of this project that impacts low-income neighborhoods. \r\n\r\nAdditionally, the impact of this project benefits local chefs and restaurants by supplying restaurants with locally sourced, organic seasonal ingredients.  Chefs will get to know their grower personally, source their ingredients locally, and more importantly participate in the promotion of this project to a wider audience.  One example of the long-term benefits of more restaurants sourcing locally and organically grown produce is the generation of more urban farming jobs in LA. \r\n\r\nThe organic method of growing food honors the social contract between our life and the land.  Introducing organic amendments to nourish the soil creates another world or beneficial microbes that, in turn, make soil healthy and fertile for plant growth.  The organic method of managing pests with companion planting and habitat restoration for birds, bees, and bugs pays attention to the smaller life forms often overlooked but crucially relied upon for the healthy growth of plants.  \r\n\r\nThis project honors the complex of interdependent relationships between life in its many diverse forms and landscapes.\r\n"
How will your project impact the LA2050 “Create” metrics?:
  - Employment in creative industries
  - Concentration of manufacturing activity in LA
  - >-
    Unemployment rates (and opportunities) for the formerly incarcerated (Dream
    Metric)
Please elaborate on how your project will impact the above metrics.: "1) Employment in creative industries\r\nABF understands that this project is a unique and novel idea for LA as this region faces two major growing challenges of reintegrating the rapidly increasing number of persons released from prison and secondly, transforming food deserts in its urban areas into food oases.  In light of this, ABF’s project of urban farming with the formerly incarcerated is, by its very nature, a creative industry.  The impact of urban farming to create opportunities for the reintegration of the formerly incarcerated is a creative industry requiring multiple skill-sets.  \r\n\r\nBeneath this project’s obvious benefits of healthy food, there is a complex web of interdependent relationships strengthened by a shared belief that reintegrating the formerly incarcerated through urban farming is good for all persons and spaces.  This re-affirms the core belief that animates this project: no life or space in LA goes to waste.  Sharing the story of this impact to an LA region that is vastly diverse is no easy task and requires creativity and multiple skill-sets.  This requisite of creative skill-sets makes this project implementation a creative industry.  \r\n\r\n2) Concentration of manufacturing activity in LA\r\nABF understands that this project will increase the concentration of manufacturing, particularly agricultural, activity in LA.  The impact of ABF’s urban farms in LA will generate a large concentration of agricultural manufacturing that includes local composting and soil amendments, irrigation supplies, greenhouses and other infrastructural elements that ensure a successful urban farming enterprise.  ABF’s urban farms will also create harvest and delivery systems that will increase the manufacturing of small local storage structures. \r\n\r\n3) Unemployment rates (and opportunities) for the formerly incarcerated (Dream Metric)\r\nABF creates many opportunities for the formerly incarcerated and the communities where they reintegrate and farm.  The employment opportunities within an urban farm enterprise accommodates the diverse backgrounds of formerly incarcerated women and men and their multiple skill levels.  Urban Farming provides unique and dynamic opportunities for the formerly incarcerated to interface with diverse constituencies that range from low-income neighborhoods to high-end restaurants.  This valuable connectivity opens more possibilities for the formerly incarcerated to experience and participate in social and employment mobility.  \r\n"
Please explain how you will evaluate your project.: "ABF will measure short-term and long-term successes through a process of evaluation that includes retreats, assessments, and feedback cards.  \r\n\r\nReviewing and recording long-term successes takes place in the space of ABF’s annual 3-day retreat with staff and urban farmers.  This opportunity affords ABF and its partners to reflect upon the most poignant challenges and accomplishments over the course of a year.  \r\n\r\nThe formerly incarcerated participants in ABF’s urban farmer training program will have regular check-ins with ABF staff and will complete a program assessment form upon completion of their experience.  \r\n\r\nIndividuals and families in low-income neighborhoods will have an opportunity to evaluate their supply of hyper-local healthy foods with feedback cards.  Chefs and restaurants also have an opportunity to evaluate their produce and interaction with ABF through feedback cards as well.  \r\n\r\nABF values this process of evaluation and takes into account the feedback from the constituencies it interacts with in order to improve its programming and services and strengthen its impact.  \r\n\r\n"
What two lessons have informed your solution or project?: "ABF and its partner-organizations present a solution to the dilemma of human isolation that is grounded in human integration and interdependence.  \r\n\r\nFurther, this project of creating opportunities for integration and interdependence are informed by these two lessons; firstly, principles of restorative justice and secondly, kinship with persons currently and formerly incarcerated.  \r\n\r\nRestorative Justice places emphasis on healing the harm caused by crime and requires the participation of the victim and offender and community to address this harm and work together to restore these relationships.  Restorative Justice principles inform this project’s emphasis on the ecology of interdependence among the formerly incarcerated, the communities and the landscapes they return to as all major stakeholders in the survival and well-being for one another. \r\n\r\nUltimately, this project rests upon a foundation of kinship where persons and organizations, regardless of past history, are inextricably connected.  This connectedness made available through urban farming presents an impactful solution for human isolation. \r\n\r\nThe influence of restorative justice principles upon ABF’s high performance team that remains grounded in kinship with those currently and formerly incarcerated ensures that this project will continue to invite collaborations to create an LA that is together our LA.\r\n"
Explain how implementing your project within the next twelve months is an achievable goal.: "High Performance Team\r\n\r\nThe implementation of this project is feasible and achievable because of the deep commitment from ABF’s high performance team and the spirit of collaboration with its partner-organizations.  Members of ABF’s high performing team have extensive entrepreneurial experiences within the sphere of social enterprises and non-profit organizations.  \r\n\r\nABF’s team shares an expertise in working with persons currently and formerly incarcerated over the last 10 years.  Our staff’s background in restorative justice ministries inside juvenile halls and prisons and professional experience with employing and training persons formerly incarcerated inform our solution that forging real human connections helps to resolve the harmful effects of human isolation and alienation, and furthermore, consolidates the community’s well being.  \r\n\r\nThis foundation of experiences and skills make it possible for ABF’s high performing team (in collaboration with new partner-organizations) to develop this reintegration project of urban farming with the formerly incarcerated in local communities for a better, stronger LA.\r\n\r\nTools and Skill-sets for Urban Farming\r\n\r\nThis project is achievable because ABF has operational capacity with its sets of tools and skills.  Trained in building and manufacturing raised beds and irrigation installation, ABF’s high performance team builds out urban farm plots employing cohesive, efficient and sustainable methods.  The breadth of ABF’s team’s professional experience in training and employing formerly incarcerated persons makes effective the expansive effort to recruit, train and employ more formerly incarcerated persons. \r\n\r\nExtended Support Network \r\n\r\nABF has an advantage with a large network of professional support for different dimensions of this project.  ABF’s urban farms benefit from the volunteer efforts from students and staff at the Department of Landscape Architecture at Cal Poly Pomona.  Volunteer Master Gardeners supply a stead stream of knowledge in strategizing sustainable growing methods in LA microclimates.  Beyond the support for ABF’s urban farm design and growing methods, our urban farmers have access to volunteer mental health support from licensed therapists.  \r\n\r\nRecognizing the intensity and enormous scope of work required to support the successful reintegration of formerly incarcerated persons, ABF continues to engage other organizations to share resources, combine efforts and enlarge its impact.\r\n"
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "ABF anticipates that one major challenge to the implementation of this project is also its likely reason for success.  At this stage, one particular challenge for the implementation of this project is its uniqueness and novelty in LA.  This project is unique insofar as it intends collaboration with partner-organizations beyond namesake.  \r\n\r\nABF will install urban farms within the properties of partner reentry organizations and train its residents as urban farmers who are responsible for growing food in LA’s food deserts.  This is a unique and novel project in an LA that faces the hard challenges of welcoming the influx of released prisoners and redressing the problem of its food deserts with the establishment of urban farms.  \r\n\r\nThese rapidly growing challenges are moving at a record pace, and the scope of work to garner community buy-in and support is a slower process.  ABF’s strategy to this challenge of the recent rapid release of prisoners and the prevalence of food deserts is a process of enriching the life of the communities that house our urban farms by supplying the neighborhood with healthy food.  \r\n\r\nABF anticipates that another major challenge to the implementation of this project is the risk of relapse and recidivism with the formerly incarcerated workforce.  From our background of employing and training formerly incarcerated persons, ABF’s high performing team has a heightened awareness of the higher risk of relapse among formerly incarcerated persons.  The reentry process is fraught with its set of challenges, and a person with a past substance abuse history, for whatever reason, may relapse.  \r\n\r\nAside from substance abuse, formerly incarcerated persons may have another set of personal challenges that could inhibit a readiness to work consistently and committedly.  ABF and its partner-organizations plan to navigate through this anticipated challenge and ensure successful implementation through its larger and combined network of support services that include health professionals equipped to respond to relapse.\r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - 'Infrastructure (building/space/vehicles, etc.)'
  - Education/training
  - 'Technical infrastructure (computers, etc.)'
  - Community outreach
  - Quality improvement research
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/create-la-the-place-where-no-space-or-life-is-wasted/img.youtube.com/vi/Eg3e5xfocOk/hqdefault.jpg
youtube_video_identifier: Eg3e5xfocOk

---
