---
published: true
organization_id: '2014035'
year_submitted: 2014
category: create
body_class: banana
project_id: '4102072'
title: FORT (Resident Makers Program to help creatives start their own companies).
project_summary: >-
  FORT plans to expand its current operation and launch Resident Maker Programs
  (complete with DIY workshops, 3D Printing & Ted-like talks).
project_image: 'https://img.youtube.com/vi/kNqNTSXVqsI/hqdefault.jpg'
project_video: 'https://www.youtube.com/embed/kNqNTSXVqsI'
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - SGV
  - SFV
  - SOUTH BAY
  - WESTSIDE
Please identify any partners or collaborators who will work with you on this project.: "Yes, all of the following mentioned collaborators are confirmed:\r\n\r\n\r\n•\tNo Right Brain Left Behind- FORT will build up and off of the success of past and future recipients of LA2050.  We are partnering with NRBLB by giving free DIY workshops to kids of the Salamander Project who struggle with challenging circumstances. Such workshops will go hand in hand with their educational curriculum (ie if they are learning about electricity/Thomas Edison FORT will give a workshop to them on wiring lamps).  \r\n\r\n•\tHabitat for Humanity- will help supply us with reclaimed materials from which we build in return we help build homes and give workshops.\r\n\r\n•\tGood Planet- will also provide FORT with building materials.  The supply from Good Planet comes directly from recycling the wasted wood, rope, metal, ect. that is ever flowing from commercial and movie set productions.\r\n\r\n•\tVEDC (Valley Economic Development Center)- will take special care of our FORT Resident Makers with one on one sessions with expert professionals who will help them start their own business after launching their product through FORT.\r\n\r\n•\tMentor Matchmaker- will provide our FORT Resident Makers with experienced mentors to guide them in their journey of creating a career out of their creative passion. \r\n"
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  FORT plans to expand its current operation and launch Resident Maker Programs
  (complete with DIY workshops, 3D Printing & Ted-like talks).
Does your project impact Los Angeles County?: 'No'
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - San Gabriel Valley
  - San Fernando Valley
  - South Bay
  - Westside
What is your idea/project in more detail?: >-
  At FORT we want to take the feeling of community, construction, creativity,
  and design, which we innately held in our adolescence (building forts), and
  use it to empower and reinvigorate the Los Angeles population as a whole.  We
  have accomplished this on a small scale out of our workshop in DTLA, but are
  ready to take it to the broader community.  Through our Resident Maker
  Program, local residents will learn from the best, refine their ideas, and
  launch their creative products through FORT.  Resident Makers will agree to
  give workshops themselves a ‘pay it forward’ like fashion.  Because of this
  crucial feature, the Maker community can be self-generating, viral, and
  scalable, thus increasing and magnifying its social impact.  
What will you do to implement this idea/project?: "Currently FORT operates as a company that leverages reclaimed materials to create beautiful pieces of furniture.  We also host DIY workshops, where community members learn from prominent artists/makers, make goods from reclaimed materials, and organize monthly events focused on community and design.  Our inventory is available through our website and by appointment.  FORT would like to evolve this established base into a new creative paradigm for social impact, empowering Los Angeles and creative industries/businesses at large.  \r\n\r\nImplementation would consist of 5 integrated components:\r\n  \r\n•\tRolling out our FORT Resident Maker Program.  This unprecedented element would consist of selecting local makers each month and giving them the tools they need to launch their creative product.  We would provide necessary allotted space for them to work in our workshop, required machinery including 3D printers, professional photography for their piece, space in our online marketplace, as well as the mentorship and resources needed to make it in the world as a newfound artisan entrepreneur.  \r\n\r\n•\tAcquisition and build-out of new location.  FORT is currently housed out of a 1,650 sq loft in DTLA.  A bigger space with more accessibility and visibility would be a great help to us in this endeavor.  \r\n\r\n•\tFulfill already secured partnerships (elaborated upon in a subsequent question below).  FORT has collaborated with some incredible organizations in our time of operation.  In our efforts to make LA the best place to create in 2050 we will partner with the following:\r\n\r\no\tNo Right Brain Left Behind\r\no\tHabitat for Humanity- \r\no\tGood Planet\r\no\tVEDC (Valley Economic Development Center)- \r\no\tMentor Matchmaker\r\n\r\n•\tEnhance our DIY WORKSHOPS by recruiting the most talented makers and designers from all over the world to share their craft with locals.  We are modeling this after Restaurant 57 who takes visiting chefs in from all over.  We will do the same by inviting worldly makers who come through LA.  \r\n\r\n•\tEstablish Pop-up workshops and DIY seminars in various neighborhoods across LA to distribute the knowledge, skills, and a platform to Angelenos from all different economic levels.\r\n"
How will your idea/project help make LA the best place to CREATE today? In 2050?: "It is the age-old adage, “Give a man a fish…teach a man to fish...”  Through the reverberating effects of our Resident Makers selling their products and acquiring the tools to become entrepreneurs themselves, FORT will facilitate an environment in which creatives can flourish in Los Angeles for years to come.  In exchange for the platform to learn, refine, and launch their creative products through FORT, Makers will agree to give workshops themselves in a ‘pay it forward’ like fashion.  Many of such workshops will be given in a pop-up like fashion in underserved areas of LA.  This feature will grant children from struggling communities activities that will allow them to explore creative potentials.  We will show them that through the usage of reclaimed materials they too can build and create things with very little to start.\r\nAs for the future, 2050 will become a year in which all people in LA have the community resources to make financial means through their own creative endeavors.  Given the community that we are building with the workshops and events centered around design, it will be much more commonplace for Angelenos to congregate on these common grounds.  The divide of East LA and West LA will blur as we all gather mid-point in DTLA to remember that young, playful spirit of building forts.  In addition to the social impact FORT will have, we will also have an environmental impact as the increased usage of reclaimed materials will correspondingly decrease the waste accumulating in landfills.  In the year 2050, building with all new materials will become a thing of the past.  Our population will have made the realization that most of what we need to build with, both intellect and material, is already here…just waiting for us to behold.  That by reclaiming the goods and materials we already have readily available, we can make anew through great design and ingenuity.  Expanding the current operations of FORT would be an incredible step towards such a reality.  "
Whom will your project benefit?: "•\tThe children of the Salamander Project (last year's recipient of LA 2050) as well as youth from other underserved communities will learn skills and explore their creative potentials through free workshops from FORT. \r\n\r\n•\tCreatives who are chosen for the FORT Resident Maker Program will launch their product and be given resources to embark on their businesses.\r\n\r\n•\tAdult participants of the DIY WORKSHOPS given at FORT will build connections as well as pieces they get to take home with them.\r\n\r\n•\tAudiences of the FORT ‘Ted’-like talks from great creative thinkers and designers will leave inspired and excited about new perspectives.\r\n\r\n•\tParticipants of our monthly round table dinner party will enjoy one another and provocative questions/table discussions about how to foster a better LA culture.\r\n\r\n•\tOlder generations (as we will seek out retired craftsmen and makers to give talks and workshops) will pass on their incredibly valuable knowledge and experience the joy of knowing they are a necessary component of our society.\r\n\r\n•\tLocal colleges, Jacqueline Sharp (FORT founder) through speaking engagements  will give talks about entrepreneurialism and creating your own job in this new economy.\r\n\r\nOverall however FORT (Resident Makers Program) will help the LA community at large because it incredibly integrated with all of the 5 categories of LA2050.\r\n\r\n•\tLEARN- Education of the arts for all ages through the DIY workshops and lectures given at FORT.\r\n\r\n•\tCONNECT- FORT hosts community events, dinners, talks, and a monthly event that features a creative elderly who has much to share…bridging the gap between the young and the old.\r\n\r\n•\tLIVE- The environmental impact that FORT would have would come from diverting materials away from the landfills through the primary use of reclaimed materials.\r\n\r\n•\tPLAY- What better way to play than to build with new friends?\r\n\r\n\r\n"
How will your project impact the LA2050 “Create” metrics?:
  - Employment in creative industries
  - Arts establishments per capita
  - Concentration of manufacturing activity in LA
  - Patents per capita
  - Jobs per capita
  - Minority- and women-owned firms
  - Gini coefficient
  - Number of high-growth startups
  - Venture capital investment
  - >-
    Measures of cultural and global economic influence (“soft power”) (Dream
    Metric)
  - >-
    Recruiting and retention rates at local higher education institutions (Dream
    Metric)
  - >-
    Percentage of graduates from local higher education institutions that remain
    in LA County 5 years after graduating (Dream Metric)
  - >-
    Unemployment rates (and opportunities) for the formerly incarcerated (Dream
    Metric)
Please elaborate on how your project will impact the above metrics.: "FORT (Resident Makers Program) will impact several of the above metrics and below we have highlighted a few:\r\n\r\n- Increase employment opportunities in creative industries. Project Fort will have an exponential impact on job employment in creative industries by providing emerging artists and makers with: (i) workshops to design and build; (ii) a marketplace to sell their product; and (iii) business education, mentorship support and networking opportunities.  This project will create sustainable local owned and operated businesses which will directly increase employment opportunities for artists, makers and their employees. \r\n\r\n- Increase Arts establishments per capita.  Through providing a platform for artists and makers to design and build their own products and start their own business the Resident Maker Program will directly increase the amount of design workshops, art and furniture galleries and other arts establishments per capita in LA. \r\n\r\n\r\n-  Concentration of manufacturing activity in LA.  All design and manufacturing of products created through the Resident Makers Program will be done in workshops in LA and products will be made with reclaimed materials which are sourced locally through Habitat for Humanity, Good Planet and other local suppliers. \r\n\r\n-  Patents per capita. Through innovative and cutting edge designs created through the Residents Maker Program and through collaborative partnerships with innovative company's such as Changing Environments http://www.changing-environments.com/ this project has the potential to generate 10 patents in the first year. With exponential growth every year thereafter this project will directly increase the amount of patents per capita in LA in 2050.\r\n\r\n-  Minority and women-owned firms \r\nFORT's owner (Jacqueline Sharp)    is both a woman and minority and FORT understands and appreciates the obstacles woman and minorities often face in launching their own business. Through FORT's success it has served as a strong example to the community of the opportunities available to both minorities and woman. While FORT seeks to directly increase the amount of minority owned firms in LA by 2050, FORT's vision is to empower and support artists and makers of all genders, races and economic backgrounds to turn their creative passions into successful businesses. \r\n\r\n-In addition to these we will impact the environment by diverting raw materials away from the landfills and encouraging others to do so at home."
Please explain how you will evaluate your project.: "As a growing business it is critical to have a strategic plan to measure success. FORT uses a well-known tool: OKRs. The system made famous first by Intel and now by Google asks all employees to outline their major objectives and the quantifiable actions it'll take to achieve them. It’s a technique designed for accountability and enforced with scores.\r\n\r\nOKRs are made up of a high level objective, a more detailed description of why that objective is important, a summary of how the objective aligns with the broader goals of both the person’s team and the company, and the three to five key results that will help them achieve that goal (see below for examples).\r\n\r\nWhen personal objectives are directly and clearly connected to the broader goals of the company, they’re suddenly more inspiring, less myopic. FORT will make them public so everyone can see what’s on their co-workers’ plates and see how other Resident Makers are doing with their objectives and key results. That way, OKRs become a built-in way for people to ask for resources, or easily spot where they can come to their colleagues' aid or collaborate with other Resident Makers.\r\n\r\nFORT's OKR systems will include the following components:  \r\n-The ability to track results on a quantitative basis. Key results are not general or subjective actions you plan to take. They should always include numbers to make it clear how much has been achieved. For example, how many Resident Makers have successfully gone through the program each quarter. \r\n\r\n-Make it something people look at, every quarter, every week, every day.  This consistency turns goal-setting into a habit and changes how people think about their work and approach their everyday to-dos. FORT will require specific milestones from it's employees and Resident Makers to help ensure that they are meeting up to the standards of the program and achieving their personal objectives.  For example we will be charting revenue. \r\n\r\n-OKR's have to be a stretch. Most people wouldn’t consider 70% to be a good grade, but for OKRs that’s just about perfect due to the ambitiousness of the goal set in place.  FORT wants its employees and Resident Makers objectives to be lofty enough to push them beyond their limits. It forces the tough conversations about what's truly needed to beat expectations and make a difference that will materially impact LA in the year 2050.  With this, we will chart number of workshops given and numbers of participants from all over the city."
What two lessons have informed your solution or project?: "When Jacqueline Sharp (FORT founder) started her business she did so with very little.  It seemed daunting at times, but she quickly learned how to get better with each step, \"I started with a Craigslist ad for a $50 table saw and a ton of YouTube clips. I’ve been learning every day since. Whenever I can, I surround myself with people who are more skilled, more knowledgeable, and I ask a lot of questions. I have found that if you are pleasant and genuine, people who love their craft often love to share it with others.\" (quote from recent Darling interview http://darlingmagazine.org/the-dreamer-embodied-fort/)  From this experience she realized a need for mixing the experienced with the inexperienced.  The experienced makers will lead the workshops teaching those less knowledgable, and the inexperienced workshopper's excitement will fuel the instructors reminding them of the joys of their craft.  Both parties have so much to offer one another.\r\n\r\n\r\nShe also learned that the \"barriers are only as strong as you make them. I’ve been asked if it is difficult being a girl, a minority, not having an MBA, not having had start-up funding, not having had necessary skill sets, the list goes on! Fortunately, I rarely pay notice to such things. I was busy working and too excited to feel these things were a hindrance. In time, because I was comfortable with who I was and where I was in life, all of those ‘obstacles’ ultimately became assets. For others, the fact that I was a woman was interesting; a minority, memorable; undereducated, atypical; underfunded, resourceful; and under skilled, teachable. It is all about perspective and working towards the fulfillment of your own potential.\" (quote from recent Darling interview http://darlingmagazine.org/the-dreamer-embodied-fort/)  From this experience Sharp realized that a lot of people focus on the things that can hold them back from incredible ventures when all they really need is to look at themselves from another perspective.  This has led to Jacqueline Sharp's excitement in working with entrepreneur makers and wanting to give them a space they feel powerful coming from.\r\n\r\nRead more about her story in a Forbes.com feature:  http://www.forbes.com/sites/sarahmckinney/2014/01/06/creating-beautiful-furniture-from-reclaimed-materials-the-inspiring-story-of-jacqueline-sharps-fort/"
Explain how implementing your project within the next twelve months is an achievable goal.: >-
  Because FORT is already an existing workshop/retail we already have that side
  of the model in place.  That is a huge foundation to begin from.  We plan to
  launch the Resident Maker's Program and that we have extensive networks and
  social media outlets to garner support from.  Jacqueline Sharp (FORT founder)
  is a part of AMEX's CEO Bootcamp network, a Tory Burch Foundation Alumni, a
  Goldman Sach's 10,000 Small Businesses Alumni and has many other local
  organizations she's worked with as well.  These networks will assist in the
  marketing of this program and recruitment of entreprenuers.   Build out of a
  space will take a relatively short amount of time as a workshop takes little
  glitz, glam, or cosmetic transforming.  We mostly need machines and shelving
  for materials.  Building out this new and improved website which includes a
  Marketplace for our Resident Makers will take an estimated 3 months.  
  Recruiting various community organizers from all over the city will take a few
  months and a lot of planning.  We want to collaborate with local community
  organizers to optimize the benefits of 'Popping' in to give our workshops. 
  All in all the project will be fully operational with in 8 months time.  
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "FORT currently operates as a small business with a smaller customer base.  We anticipate some growing pains especially in the operations department of scaling up.  We have already connected with operations management consultants and found one that would be perfect for the job!  She has ten years of experience in both non-profit and for profit.  She loves the concept behind FORT and is excited to work with us if given the opportunity.  We would hire her for the onset of this new operation so that she could give us her expertise in this area.\r\n\r\nOften times there is a lot of excitement generated in the beginning of a project and then that energy tends to fizzle out.  We want to ensure that this project will be one that will carry us into the future of LA making it the best place to Create.  In order to do so we will use the aforementioned OKR's to track everyones progress as well as create individual and dynamic operational goals.  This will generate a continuous excitement.  There will also be new Makers coming in every month, with new ideas and designs keeping everything fresh and full of life.\r\n\r\n\r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - 'Infrastructure (building/space/vehicles, etc.)'
  - 'Technical infrastructure (computers, etc.)'
  - Community outreach
  - Quality improvement research
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/fort-resident-makers-program-to-help-creatives-start-their-own-companies/img.youtube.com/vi/kNqNTSXVqsI/hqdefault.jpg
youtube_video_identifier: kNqNTSXVqsI

---
