---
published: true
organization_id: '2014153'
year_submitted: 2014
category: learn
body_class: blueberry
project_id: '4102096'
title: Ignite Teaching
project_summary: >-
  Empower students to create collaborative digital projects that increase
  achievement and quality of relationships through teamwork and equity
project_image: >-
  http://maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F20940%252Fdisplay%252Fla2050.png=c570x385
project_video: ''
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - SGV
  - SFV
  - SOUTH BAY
  - WESTSIDE
Please identify any partners or collaborators who will work with you on this project.: "Dr. S K Ramesh is Dean, College of Engineering and Computer Science, and Professor of ECE at CSUN. He is on the IEEE Ed Activities Board, the IEEE-HKN Board of Governors, and the Accreditation Board for Engineering and Technology Board of Directors. Coupled with over 20 years of academic leadership as dean and department head at 2 different CSU campuses he has extensive experience working with orgs, non-profit boards and is the PI of $5.5mil US DOE grant to support and graduate minorities in CECS.\r\n\r\nHe is Chair of the IEEE Pre-University Ed Coordinating Committee responsible for global programs to encourage youth to pursue careers in CECS. Together, we will find synergies between Ignite and his programs. In addition to product feedback, we also draw upon his expertise in implementing successful outreach programs to promote CECS using external grants.\r\n\r\nDr. Michael Spagna is Dean, College of Education and Dir of the Math and Science Teacher Initiative at CSUN.\r\n\r\nHis Institute for STEM Education (ISTE) is a cross-college initiative to advance learning, teaching, scholarship, research and innovations in STEM. This will occur through collaborative partnerships with different orgs including businesses such as  Ignite. Other projects include Computer Supported Collaborative Science (funded by HP) and the creation of a math app for 8th graders (funded by Lockheed Martin).  CSUN is 1 of 11 universities to take part of Carnegie’s “Teachers for a New Era” initiative to re-envision the nation’s teacher education programs for urban classrooms and to develop evidence-based models that can be widely disseminated.  As a result, CSUN is positioned at the forefront of empirically based practices nationally.​ This will help Ignite realize our long term potential using pragmatic methods.\r\n\r\nDr. Anthony Galla is 20 year educator and current Elementary Assistant Superintendent in the LA Archdiocese. A former principal of St. Francis de Sales with classroom experience from K through college, with a majority as a Jr. high school history teacher. He also writes grants, assists with school finance policy, and contributing EdTech resources. His vast experience has helped shape Ignite during alpha. He regularly provides the group with commentary regarding EdTech and how he's seen it evolve from his various perspectives as an educator and admin. His use of Ignite will extend to its beta phase, where he will use the app to develop classroom and faculty functions.\r\n\r\nAll confirmed."
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  Empower students to create collaborative digital projects that increase
  achievement and quality of relationships through teamwork and equity
Does your project impact Los Angeles County?: 'No'
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - San Gabriel Valley
  - San Fernando Valley
  - South Bay
  - Westside
What is your idea/project in more detail?: "World renowned educationalist Sir Ken Robinson said, \"We don’t grow into creativity, we grow out of it… or rather get educated out of it\".\r\n\r\nCreativity has long been solely attributed an elite few like, artists and musicians. With Ignite, everyone is creative. When used for group projects to express student knowledge and ideas, it leads to deeper understanding of topics and teaches them the importance of social interdependence and accountability. Students build confidence by assessing and awarding each other with badges that they've earned from teachers through our peer badging system.\r\n\r\nStudents learn lifelong creative, social and psychological skills that will come back to serve them throughout their lives as they become LA in 2050."
What will you do to implement this idea/project?: "Ignite has teamed up with experienced educators in LA and across the nation to build the best collaborative digital creation tool made specifically for the classroom. From their own device, students create beautiful digital projects with help from members of their group. The types of creations that were once only possible through tools with steep learning curves like Photoshop. Students leverage text, images and videos from around the web with tools built into Ignite’s editor. Projects can be edited in real time by other members of the group.\r\n\r\nIn addition to the rich creation experience, we will build a wide range of teacher tools. We know that teachers don’t have enough time as it is so things like creating an account, classes, assignments is built directly into our workflow. We track individual student contributions and a produce progress report for teachers that clearly identifies what each student contributed. Individual responsibility can finally be fairly assessed in the group project environment with Ignite.\r\n\r\nNick Sithi, a core member of our founding team is a full-time teacher with over 9 years of experience educating the youth of LA. He not only provides crucial product feedback but also runs Ignite’s private alpha which is deployed to a group of K12 educators. During this alpha phase we are receiving crucial, real-time feedback from teachers across the nation.\r\n\r\nRight now we’re all heads-down preparing the iPad app for our beta launch in September. Soon after we will focus on the following four areas;\r\n\r\n1. Cross Platform\r\nAlthough we initially launched with the iPad we plan to have cross platform support by Q1 2015. This means that Ignite will run on any tablet, PC, and across all major browsers. We will make sure any school can use Ignite regardless of their previous technology decisions (Chromebooks, iPads, etc).\r\n\r\n2. Teacher Tools\r\nIt’s paramount that teachers have the ability to assess individual contributions to the project, check for plagiarism, and manage student workflow. Teachers will be provided with clear reports that provide this key information.\r\n\r\n3. Primary school use cases\r\nOnce 1 and 2 are achieved, we will focus on making Ignite malleable for primary school use cases. The earlier we can get kids to create, the better. However, the ability of a 3rd grader is very different than that of a 7th grader. Teachers will have the ability to customize the Ignite’s creation process to take into account the varying skills levels."
How will your idea/project help make LA the best place to LEARN today? In 2050?: "According to Creating Minds*, “At age 5 we use 80% of our creative potential but by age 12 we drop to as low as 2% and stay there for the rest of our lives.”\r\n\r\nToday, LA has roughly 640,000 students in K12 among its 1000+ schools spread over 720 square miles. We believe a majority of those kids would not consider themselves creative because they aren’t labeled as artists or musicians. These are the same kids who are or going to be subject to an increased focus on collaboration in the classroom through the new Common Core Standards**. This is especially true in the subjects of  English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects.\r\n\r\nThrough Ignite’s blend of creativity, collaboration, and confidence building we are empowering teachers all over LA to give their students the critical experiences they need be better citizens of LA and the world. They learn how to CREATE, leverage technology to further their own understanding of subjects, explore new ideas, define their own interpretation of theories, contemplate subjects from different angles, and articulate things in their own personal way. They learn to COLLABORATE, how to communicate, how to navigate disagreements, how to voice their opinion, how to use other’s opinion to shape new ideas, understand how their individual efforts impact the success or failure of the group. They understand the importance of RECOGNITION of their own hard work as well as the hard work of others.\r\n\r\nWe believe all these skills must be learned in the most crucial time in their lives when they are most malleable, that is,starting from kindergarten all the way up to high school. This is why Ignite is important TODAY.\r\n\r\nTODAY, there are the 640,000 students in LA trying to find out who they are, navigate adolescence, young adulthood, trying to form their own opinions, make friends etc. In 2050, they will be LA. They will be our inventors, creators, makers, entrepreneurs, educators, inspirers and leaders. The future Elon Musks, Barack Obamas, Sheryl Sandbergs of the world. And why? Because LA believed in a kind of 2014 that valued creativity, collaboration and technology in the classroom.\r\n\r\n* creatingminds.org/articles/age.htm\r\n**www.corestandards.org/ELA-Literacy/CCRA/SL/"
Whom will your project benefit?: "Any student from kindergarten to high school. The younger they start Igniting, the better, because the sooner you explore creativity and collaboration, the more time you have to sharpen those skills. We want to make creativity a habit we learn as soon as we can start to read and write. By LA2050, we believe no one should be saying, “I’m not creative enough to do [something]”. They _will_ do it because of initiatives like Ignite that taught them how to think creatively especially with other collaborators. Students will take the skills they’ve learned using Ignite with them into the world, long after their formal education careers are over and pay off in dividends in every single aspect of their life.\r\n\r\nTeachers will also benefit from Ignite through its assessment features. Ignite generates a progress report for each group, detailing the efforts of each student involved. Concrete data will allow teachers to fairly assess and acknowledge contributions made by each group member, creating equity during assessment. Teachers can trust their students to become more responsible, knowing that they are held accountable for their actions. \r\n\r\nAnd where and when did it all begin? LA2014"
How will your project impact the LA2050 “Learn” metrics?:
  - HS student proficiency in English & Language Arts and Math
  - >-
    Student education pipeline (an integrated network of pre-schools, K-12
    institutions, and higher education systems that prepares students for
    seamless transitions between high school, higher education institutions, and
    the workforce) (Dream Metric)
  - >-
    Meaningfully increase the creativity and collaboration of our youth for a
    better LA2050 workforce
Please elaborate on how your project will impact the above metrics.: "--- HS student proficiency ---\r\nIn order for students to learn more deeply and effectively, we must encourage them to think critically and creatively. They must question, hypothesize, pursue, fail, try again, collaborate constructively, communicate effectively and achieve together. Through this process, students develop the skills they need to learn how to develop deeper understanding of anything around them, not just in school. It prepares them early on for the real world situations they will face academically, socially, and professionally.\r\n\r\nThere is no limit on what subjects teachers can use Ignite for, but there is a direct fit for subjects such as English, the arts, and math. Assignments such as “The Great Gatsby and the 1920s”, “Popular Sovereignty and Slavery”,  “A Day in the Life of an Impressionist” and “Game Theory Mathematics: The Prisoner’s Dilemma and the Paradox of Rationality” are but a few of the endless projects. As students put together their Ignite project, they are researching and analyzing topics to create their own interpretations. Ignite makes it really easy to include images, text and videos from the web while still retaining proper attribution/citation. For language arts, student essays and compositions take on a more fun, interactive approach. \r\n\r\nRegardless of subject, Ignite empowers students to learn how to construct, organize, test and digitally express their own thoughts and work with their collaborators to form a cohesive storytelling experience. \r\n\r\n--- Student Education Pipeline --- \r\nOne of our goals is for Ignite to be integrated in classrooms as early as kindergarten. Ignite will follow the student’s creative and collaborative growth as they enter new grade levels. We will build a comprehensive suite of reporting, analytics, and assessment tools to help teachers better understand their new students as they transition into and out of their classrooms. \r\n\r\nWe believe in a LA2050 that’s filled with creative citizens. The average creative skills of a Los Angelino in 2050 should be 10x more than that of a typical resident in 2014. This will undoubtedly help creative industries because we want every student coming out of the educational system to be truly creative. \r\n\r\nCreating is fun. Making is fun. We are born to do it. When we take great strides to promote creativity and collaboration at a grand scale we believe GOOD things will happen. Things like meaningfully increasing employment in LA’s workforce in the year 2050."
Please explain how you will evaluate your project.: "- By the end of 2014 be in 20 schools in and around Los Angeles.\r\n\r\n- By the end of March 2015, be near 100% cross platform so that any school around the world can use it so long as they have a internet connection, PC or tablet.\r\n\r\n- Starting January 2015, a 5% month over month adoption rate (by number of students)\r\n\r\n- Mid 2015 we will work with a third party evaluation team, such as California State Northridge’s C.A.R.E assessment group, to take a deeper dive into the long term academic, social and psychological benefits of Ignite.\r\n"
What two lessons have informed your solution or project?: "#1 - November 7, 2013, was the happiest day of my life. That’s the day I became a father to a beautiful daughter named Nya. As some of you can relate to, everything changes once you have a child. I vowed that day that I would give her the best life and education that I possibly could. As any parent would do, I researched and read several books on parenting and education. Book after book, a pattern kept jumping out at me: children who are raised with an emphasis on social interdependence and collaboration are proven to lead more wholesome and successful lives. Scientific research* indicates that when students are subject to creative learning, it results in higher achievement, greater productivity, more caring, supportive and committed relationships, have higher social competence, and self esteem... the list goes on and on. So I made the decision. I’m going to do more than just put Nya through college. I’m going to do everything in my creative power to help every child that passes through our educational system become more wholesome individuals.\r\n\r\n#2 - We know that teachers want a tool like Ignite in the classroom through our extensive experience in the online digital publishing space. We’ve built apps that have been adopted by teachers around the world. These products were never built or marketed for education, but teachers still strong armed these products into their classroom. After talking to experienced educators, we realized there was massive change afoot in education. With the rise of flipped classrooms, blended learning, technology, and new education standards we want to do our part to empower students with what they need to succeed. We don’t care about the general consumer markets. We will make our mark through education.\r\n\r\n*http://www.researchgate.net/publication/224766541_Benefits_of_collaborative_learning/file/d912f4fba453f0b43f.pdf\r\n"
Explain how implementing your project within the next twelve months is an achievable goal.: "Our founding team of three is very effective at getting things done. Two seasoned engineers/entrepreneurs and an experienced educator - Micky Dionisio, Justin McCammon, and Nick Sithi. Between Micky and Justin, there is over 17 years of software engineering experience across companies such as Yahoo!, digital media agencies, and Fortune 500’s. Nick Sithi is an experienced educator with a Masters from Loyola Marymount University who teaches English a high school in LA. We will harness our experience building apps and tools for digital publishing and education in order to launch Ignite in September. We’ve also hired an additional software engineer to increase throughput. We’ve been working on this project since May 2014 and continues to be 100% bootstrapped.\r\n\r\nBy the time the grant winners are announced Ignite will already have launched. This means we will spend the next 12 months working on our strategic partnerships (as described in the collaborator section), improving Ignite using feedback from the educators who use it, and working towards our overall success metrics. Building the technology is not our main concern. We know we can build software all day long. What’s important to us is that we optimize correctly for the classrooms in LA and around the world. We need to listen, learn and collaborate closely with educators, schools and districts that use Ignite. Without them, this will never be successful.\r\n\r\nLuckily, we’re fantastic listeners."
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "Our big question for us since day one is “how do we get teachers to try Ignite in their school?”. For beta, we’ve tapped into our own personal networks to get in touch with K12 educators who are excited for our beta launch. Once we launch, we need to make sure we continue to spread Ignite into classrooms in and around Los Angeles.\r\n\r\nSecond, we’ll have a challenging time balancing the needs of public, private, and charter schools. Each type of school has its own way of doing things such as curriculum implementation, or FERPA adherence for privacy, or differentiated technology used in the classroom. We’ll need to make sure Ignite is malleable enough to support each type of school. We're confident we can do this once we start getting feedback."
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Publicity/awareness (social capital)
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/ignite-teaching/maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F20940%252Fdisplay%252Fla2050.png=c570x385.png
maker_image_id: '20940'
maker_image_file_name: la2050.png

---
