---
published: true
organization_id: '2014154'
year_submitted: 2014
category: learn
body_class: blueberry
project_id: '4102097'
title: I’LL BE THE 1 2 SEE THE LIGHT
project_summary: Service learning programs that matter for secondary students & teachers.
project_image: >-
  http://maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F21338%252Fdisplay%252FIBT1student.jpg=c570x385
project_video: ''
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - WESTSIDE
Please identify any partners or collaborators who will work with you on this project.: "Non-profits – Tree People, Heal The Bay, Kiss The Ground, Global Green and ACE.\r\n\r\nGoverning agencies – City of LA Mayor's office and their Sustainable goals. \r\n\r\nInstitutions of higher learning – partnering with film schools and Universities.  We are working with UCLA.  \r\n\r\nSecondary Schools – University High, Amino Inglewood High School, Amino Westrside Middle School, Muse School (these are confirmed) and more to come.  \r\n\r\nCREEC- CA Dept of Ed.\r\n\r\nArts and Entertainment Industry– partnering with film schools such as LA Film so students will be exposed to the entertainment industry through media projects we build with the students.\r\n\r\nThree factors critical to the success of our collaboration: 1) regular and open communication. Not a lot of institutions are used to working in such a collaborative and innovative way. There’s a lot of disconnects and “re-invent the wheel” stuff in the non-profit world and entertainment industry here. By putting the focus on the youth and not on any one organization, we give the power over to the people and encourage a much higher level of organization. There’s a learning curve in and of itself in this collaboration. We are staffed at IBT1 with experts in empowerment and leadership training and fully intend to have one of the first things we do to be to inculcate the collaborating partners into our new model of thinking. We need to walk our talk for it to work. In addition, we are staffed amply to do regular follow up with our partners and support a regular open flow of communication clearly. 2) acknowledgment for the system as it currently works. We do have our feet on the ground, even if our vision is to shoot for the stars, so to speak. We know we have to be palatable to the schools learning agenda, especially with standardized testing, so we are partnering with CREEC to ensure we are doing this in a way that’s approachable enough for the schools that they’re able to fit it in their scheduling. 3) a clear plan. High level collaborations are awesome, but they need clear strategy and direction. Through the discipline comes the freedom. We have big goals, but they start with small strategic steps. We have very clear game plans about who to engage in year one, and what we need from who to make this work. We constantly re-evaluate and course correct, but are savvy to the need for specific and measurable benchmark goals, especially in the early stages of partnerships until a more naturalorganic rhythm starts to unfold. \r\n"
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': Service learning programs that matter for secondary students & teachers.
Does your project impact Los Angeles County?: Yes (benefits a region of LA County)
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - Westside
What is your idea/project in more detail?: "How do we ensure for a future where our leaders are well equipped to guide us through the impending social, economic, and environmental challenges we face as a society? How can we educate our youth in being strategic disruptors of innovation, using their talents and creativity to come up with real solutions for tomorrow’s concerns? And most importantly, how do we get this next generation of leaders to really believe in their capacity to take effective action to improve their lives and the well-being of our world without which they lack the motivation to do so? We believe it starts with creating innovative and experiential, student-driven educational and leadership programs for young adults. \r\n\r\n \r\n"
What will you do to implement this idea/project?: "Through service learning educational programs, student made documentary films, social media campaigns, youth summits, educational art installations, literature publication, and online curriculum, IBT1 encourages youth to get involved and interested in larger social issues by using inspiring, creative mediums. \r\n\r\n\r\nPresented with opportunities in the class room to address present day, real-world challenges students will take on projects that test out their critical thinking and team-building skills on issues that will immediately have an impact on their local communities, and they’ll build up their confidence in their ability to impact real change while doing it. Of course, we need to teach our youth the basics about the important global issues at hand, but it is also our responsibility to restore in them the belief that they can indeed make a difference and that their actions matter. We need to give them the opportunity to experience that they, indeed, can be the one to make a change for the better. \r\n\r\nOur premiere program based on this philosophy, SEE THE LIGHT, will launch in over 10+ Los Angeles based Secondary Schools Fall 2014. Designed to walk teachers and students through an eco-challenge that impacts their school and/or community to which they must propose and vote on a chosen project to implement as a potential solution to the presented problem. \r\n\r\nThis fall we will address the five main topics of soil health, waste management, energy, air quality, and ocean health in that particular school and group of students. Each school participating will be provided with 3 visits from an IBT1 program lead.  We will provide the following; three classroom discussions, a presentation about our program; actionable take home tool kit that addresses the eco-challenge; a sustainability plan for the school and student related to the challenge; tools for science, environmental and film clubs to launch peer-to-peer learning campaigns; access to our online tools, how to videos, social media engagement, and tracking system; comprehensive volunteer, internship, and learning database; and resources in English and Spanish language. \r\n\r\nSEE THE LIGHT will empower students to take on an eco challenge, art installations, media campaigns, and documentary films that push forward social change.  With our online portal students will be able to track their groups’ project, find and log volunteer hours, and earn points toward green products, healthy food, and scholarships."
How will your idea/project help make LA the best place to LEARN today? In 2050?: "SEE THE LIGHT is uniquely designed to take advantage of the rich resources we have in the LA metropolitan area – namely the bar-setting arts and entertainment industry and the thriving local non-profit community- and make them more available to the youth engaged in our programs. Many of these youth, especially those in the less affluent areas, would never otherwise have exposure to such resources. By creating collaborative partnerships between local non-profits (Heal the Bay, Tree People, etc.), the creative arts and entertainment industry, local governing bodies, and local schools we create a learning web for students that inspire them at a passion level so the learning flows naturally. We show them the benefits of cross-pollinating from the many sectors of society to come up with creative solutions to long-held societal problems. We create an “innovation-incubator” for our youth to nurture and build confidence in the budding leader inside. Through mentorship programs and youth summits in our programs and online community, we connect youth directly with places of potential future employment. \r\nWith SEE THE LIGHT, LA does become the best place to learn today because we bridge the gap between school and the community’s outside resources. We take the pressure off of schools to “do it all,” and we provide an avenue for outside agencies to bring their resources to the schools in an easy-to-use, immediately impactful way. What’s more, with every new year of the program, the learning web only grows stronger. The integrated community of learning that expands well beyond the walls of any one school grows bigger and more sophisticated every year. Graduates of the program can come back and act as mentors. Communications between schools, non-profits, and the entertainment industry get more frequent, more clear, and more creatively rich. We start to funnel well-trained youth into internship jobs at some of the collaborating non-profits or corporations that take part in out learning web. By the year 2050, other metropolitan areas will be emulating our model for integrated learning systems that empower our youth, our communities, and our local industries. \r\n"
Whom will your project benefit?: "The youth of today – leadership training, direct hands on experience, opportunities to direct their future success and access to meeting folks who can get them in the job market\r\n\r\nThe schools – we take over where they don’t have the capacity to take the students. Everything from teaching them emotional intelligence, conflict resolution, management skills as well as we connect schools to the local resources in the community that they wouldn’t otherwise have access to.\r\n\r\nThe industries and non-profits– entertainment industry needs vibrant young minds with innovative ideas that address real world problems. We are a key component in that pipeline, getting the best of the best youth in position to be future employees at these places.\r\n\r\nFuture generations and the planet – we are protecting the future generations of this planet by giving our best offering to this current next generation. We are teaching them from an integrated place, teaching them systems thinking so that they can address the complex problems we face with a holistic approach. We are teaching them how to be stewards of this earth. Like Einstein said “to solve a problem, you have to operate from a higher level of consciousness than the one the problem was created on.” We are offering that new high level way of thinking as a promise for a better future for all.\r\n"
How will your project impact the LA2050 “Learn” metrics?:
  - Youth unemployment and underemployment
  - >-
    Student education pipeline (an integrated network of 6-12 institutions, and
    higher education systems that prepares students for seamless transitions
    between high school, higher education institutions, and the workforce)
    (Dream Metric)
Please elaborate on how your project will impact the above metrics.: "1.\teach school project done will have specific metric developed for it (x number of plants planted in a school garden, school lunches being supplied for  certain # of kids, etc.)\r\n2.\tstudents for their projects along with their grades can recieve from IBT1 - scholarships, internships, or job placements after the year is done \r\n3.\tFunds raised by students through their kickstarter campaigns\r\n4.\tpre and post tests of kid’s confidence level in their belief in their ability to make a difference ( a survey we create for them to take before and after)\r\n5.\tnumber of kids we have in online community, number of partner organizations we have in the online community (the beginning of our learning web, what are our goals for year one)\r\n6.\tnumber of additional schools signed on for year two\r\n7.\tnumber of graduating kids who agree to be mentors for year two\r\n"
Please explain how you will evaluate your project.: "Based on project we will have a metrics to measure impact and how it aids in Climate change\r\n\r\nA project that has lasting impact for many years to come that the next wave of students can tur the project into a system for that school and/ or community\r\n\r\nStudents from our classrooms that adopt our program them graduating getting accepted to college or technical school or entering the workforce.  We track through our on line portal and aid them to make these choices. \r\n\r\n "
What two lessons have informed your solution or project?: "1. Einstein quote – “No problem can be solved from the same level of consciousness that created it.” We must address our complex worldy problem from a systems-level, and we must be able to provide children with opportunities to learn how to be systems-level thinkers. We can’t teach in isolated institutions anymore. We need to start talking to each other and working with each other. This is how we do it. \r\n2. putting youth in safe yet vulnerable positions of leadership leads to the birthplace of creativity. Brene Brown quote: “Vulnerability is the birthplace of love, belonging, joy, courage, empathy, and creativity. It is the source of hope, empathy, accountability, and authenticity. If we want greater clarity in our purpose or deeper and more meaningful spiritual lives, vulnerability is the path.” Not to sound hokey, but humans are emotional creatures. This learning program is designed to speak to and engage “all of our selves” – our emotional selves, mental selves, physical selves, etc. When we do this successfully, you ignite a kind of determination in a person’s soul that will make them strong enough to move mountains. Again, this is our most remarkable natural resource – the untapped potential of our youth to make a change. We must speak to their excellence if we want it to come out of them!\r\n"
Explain how implementing your project within the next twelve months is an achievable goal.: >-
  We will be Beta testing our program and will pilot very specifically in only
  10 secondary schools. IBT1 has created a high level team and acquired the
  contacts for a team of supplementary support, interns, administrators through
  our network. Manager roles for each school, a system of specialization in a
  larger organism – every has a clear role and knows what it is. 
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "A sucessful website to be able to have traceability and the turn key architecture to be able to create a robust site.  \r\n\r\nFunds to make this program happen and all schools to have the resources as well as funds to create an impactful project.\r\n\r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - Community outreach
  - Quality improvement research
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/ill-be-the-1-2-see-the-light/maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F21338%252Fdisplay%252FIBT1student.jpg=c570x385.jpg
maker_image_id: '21338'
maker_image_file_name: IBT1student.jpg

---
