---
published: true
organization_id: '2015132'
year_submitted: 2014
category: connect
body_class: tangerine
project_id: '4102139'
title: Los Angeles Worlds Fair Collaboration 2014-2015
project_summary: >-
  Draft a strategic plan for implementing the LAWF, and conduct an initial
  outreach for attracting support and participation.
project_image: >-
  http://maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F21921%252Fdisplay%252FScreen_Shot_2014-07-31_at_9.17.55_AM.png=c570x385
project_video: ''
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - SGV
  - SFV
  - SOUTH BAY
  - WESTSIDE
  - LA COUNTY
Please identify any partners or collaborators who will work with you on this project.: "LAWF FPC is reaching out to volunteers to support it’s efforts.  This includes a number of voluntary flex teams.  Flex teams are committees of volunteers assigned to assist it in grass roots community outreach, development of preliminary maps and plans, market strategies, and obtaining funding, among other duties and responsibilities.  The term “Flex” is used to identify them with this new type of hybrid corporation to take advantage of provisions of both profit and non-profit organizations.  This project will network the members of these teams, as necessary and appropriate, to achieve the objectives.  This application is presented under the authority of Dotty Kaminsky, Executive Director of LAWF FPC, with the approval of the Board.  The staff, advisors and volunteers listed below are assigned by her to participate in the project, as necessary. Allocation of Grant funds will be distributed by the LAWF, FPC as outlined in budget summary. The extended team will include accomplished businessmen, architects, developers, educators, government leaders, event producers, artists and entertainers, journalists, and others willing to dedicate time and effort to this cause.\r\n\r\nActive members of this team who have expressed the desire to collaborate include, but are not limited to the following by name, title, and added benefit to the project:  \r\n      Name                           \tTitle/Benefit Area\r\n•\tDotty Kaminsky, \t\tExecutive Director/ Marketing\r\n•\tRobert Vanech, \t\tBoard Chairman/Finance\r\n•\tJefferson Schierbeek, \tBoard Member, DMPC Co-Lead/ Design\r\n•\tRandy Vane, \t\t        Board Member, SVP/Marketing \r\n•\tThomas DeVoss,\t\tDMPC Co-Lead/Design\r\n•\tSharla Russell,\t\tDMPC Co-Lead/Planning \r\n•\tMarcela Oliva, \t\tDMPC Member/Design \r\n•\tJuanita Price,\t\t        ITCC Secretary/Outreach \r\n•\tLynda Wilson, \t\tITCC Co-Lead/Outreach \r\n•\tGaston Mantero,  \t\tITCC Co-Lead/Outreach \r\n•\tJohn Bollinger, \t\tAdvisor, ITCC Co-Lead/Outreach \r\n•\tEric Vollmer, Advisor,   ITTC Member; Outreach\r\n•\tBarry Howard, \t\tAdvisor/Design \r\n•\tArmen Martin, \t\tAdvisor/Legal\r\n\r\nThree factors critical to the success of this collaboration are: \r\n1.\tAvailability of sufficient funding to cover the proposed outreach effort,  \r\n2.\tDevelopment of the strategic plan to be used by participants in their outreach efforts, and \r\n3.\tEffective administration collaborative outreach efforts toward achieving the overall objectives of the project.  \r\n"
Please describe yourself: Proposed collaboration (we want to work with partners!)
'In one sentence, please describe your idea or project.': >-
  Draft a strategic plan for implementing the LAWF, and conduct an initial
  outreach for attracting support and participation.
Does your project impact Los Angeles County?: Yes (benefits all of LA County)
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - San Gabriel Valley
  - San Fernando Valley
  - South Bay
  - Westside
  - >-
    The project will reach out to communities around the County.  The LAWF will
    develop hub and satellite fairgrounds distributed around the region in close
    proximity to over 130 communities and 88 cities in the County.
What is your idea/project in more detail?: "A.\tConnect the dots between communities and cities in this region using the rail network as the backbone of the LAWF\r\nB.\tEstablish a blueprint for public and private participation in LAWF.  \r\nC.\tInform, attract and interact with the public through multiple social media channels. \r\nD.\tDraft plans, strategies, criteria, standards, and procedures for locating and acquiring land, and design and development of venues for fairgrounds and ancillary community development, beginning with “Pavilion Zero”, the initial administrative headquarters and showcase of the LAWF.  \r\nE.\tSet in motion the outreach program for connecting diverse ongoing projects and events in the region to the LAWF.\r\n\r\n"
What will you do to implement this idea/project?: "The following process is proposed to implement the project during the grant period:\r\n•\tReach out to hundreds of social entrepreneurs, students and teachers and will engage them in considering the most astonishing “WHAT IF” of their entire lives- the prospect of Los Angeles blossoming into a major world cultural capital that will be the envy of New York, London, Paris, Berlin, Tokyo, et al! \r\n•\tReach out to government, trade, commerce and culture organizations, LA Metro, Gateway Cities Council of Governments, Regional Chambers of Commerce, ports, airports, unions and trade associations, Sister Cities International members,  Los Angeles Consular Corp,  California Congressional Delegation, Board of Supervisors, mayors and councils of Los Angeles and other cities in Greater Los Angeles, Sports associations, Schools, Colleges and Universities, Hospitals and Health organizations, Fair, Festival and Event producers and operators, Television and Film producers and operators, Theme park operators.\r\n•\tDevelop a strategic plan, organization, scope, budget, schedule and strategy for implementation, including a blueprint and master list for Pavilion Zero, raising funds, and collaboration with and outreach to diverse community organizations.\r\n•\tNetwork officers, team members and advisors of LAWF FPC as listed below.\r\n•\tDevelop criteria, standards, and procedures for locating and acquiring land, and design and development of venues for fairgrounds, beginning with the initial venue, “Pavilion Zero”.  \r\n•\tPromote competition to obtain schematic design proposals for Pavilion Zero.\r\n•\tIdentify prospective sites for fairgrounds around the region.\r\n•\tKeep records of the strategic plan and outreach efforts.\r\n•\tDevelop a list of resource interest in active participation and collaboration. \r\n•\tStage initial events during this year organize and promote of the LAWF.\r\n•\tCollaborate in publishing and post a calendar of events, fairs, and/or festivals promoting the LAWF.\r\n•\tArrange contacts and meetings to explore and identify ways in which individuals and organizations can participate and collaborate in promoting the LAWF in the immediate future. \r\n•\tReport progress on a monthly basis.  \r\n•\tA final report setting forth the progress of the project in the in terms of the key LA2050 metrics and indicators.\r\n"
How will your idea/project help make LA the best place to CONNECT today? In 2050?: "Over the next decade and beyond the LAWF enterprise will make significantly greater contributions to making LA the best place in terms of metrics in all categories, Create, Learn, Connect, Play, and Live, including the following:  \r\n1.\tAttract 1000 companies and 100 countries to participate.\r\n2.\tPromote livability, sustainability, mobility and community improvement.\r\n3.\tConnect communities around the region culturally and economically\r\n4.\tProduce easy access to clean, safe, and sustainable venues which promote enjoyment of the natural environment, arts and cultural resources, local beaches, waterways and open spaces. \r\n5.\tStimulate the development of thousands of safe homes, neighborhoods and playgrounds.    \r\n6.\tIntroduce vibrant park and play space accessible to every child for afterschool and vacation enrichment programs, and will enhance. \r\n7.\tBring joy to neighborhoods throughout the region with fairgrounds and venues of which all residents can be proud.  \r\n8.\tFoster volunteerism and collaboration on a wide scale.  \r\n9.\tGenerate hundreds of thousands of jobs and new businesses,\r\n10.\tSustain many existing businesses.  \r\n11.\tGenerate demand for tens of thousands of affordable homes to house employees and their families. \r\n12.\tStimulate demand for numerous hotel rooms.\r\n13.\tProvide priceless returns of social good on an epic scale never seen before.\r\n14.\tHave a long term sustained economic impact on Los Angeles.\r\n"
Whom will your project benefit?: "The present Countywide outreach will reach as many people as possible, given available resources, to inform and provide opportunities for participation and support of the LAWF.  Over the next ten years the LAWF is expected to have the following benefits:\r\n1.\tCreate over 300,000 sustainable jobs in the region during development and operation.  \r\n2.\tAttract 100 million visitors from around the Nation and the World to Los Angeles.  \r\n3.\tStimulate community improvements in over 88 cities and 130 communities in the region.\r\n4.\tStimulate development of numerous hotels to handle the increased tourism.\r\n5.\tStimulate the construction of tens of thousands of new homes and apartments, numerous parks and sports facilities, retail and manufacturing businesses, educational facilities. \r\n6.\tGenerate billions of dollars in tax revenues which will be available to reinvest into local communities. \r\n"
How will your project impact the LA2050 “Connect” metrics?:
  - Rates of volunteerism
  - Voting rates by race
  - Attendance at cultural events
  - Number of public transit riders
  - Participation in neighborhood councils
  - Percentage of Angelenos that volunteer informally (Dream Metric)
  - Government responsiveness to residents’ needs (Dream Metric)
  - >-
    Transit-accessible housing and employment (the share of housing units and
    percentage of jobs that are located within a half-mile of transit) (Dream
    Metric)
  - Total number of social media friends (Dream Metric)
  - Attendance at public/open street gatherings (Dream Metric)
  - Residential segregation (Dream Metric)
  - Access to free wifi (Dream Metric)
Please elaborate on how your project will impact the above metrics.: "During the first year volunteers and collaborators in the enterprise will contribute toward making LA the best place to Contact people in the local, national and international communities throughout the Greater Los Angeles region.  The enterprise will contact chambers, councils, associations, volunteer organizations, schools and colleges, public officials, and social media friends to attend public gatherings, presentations, and cultural events which promote the LAWF. These activities will have impacts on the metrics, as follows:\r\n\r\n1.\t LA Metro officials will be contacted to obtain support and collaboration in acquiring property and development of fairgrounds at and around Metro Rail and Metro Link stations in the region and increase public transit access. \r\n2.\t Government leaders and officials will be contacted to obtain support and collaboration in promoting community events and improvements associated with fairgrounds.  \r\n3.\tCivic meetings will be scheduled to attract greater public participation in the enterprise. \r\n4.\tEthnic and minority communities will be enlisted to collaborate in the scheduling events, and in the planning and development process.  \r\n5.\tLocal ballot measures will be suggested to engage communities to support the acquisition of land and fund development of community facilities associated with the enterprise.  \r\n6.\tAffordable housing development close to fairgrounds and accessible to public transit and employment will be incorporated into the enterprise plan.\r\n\r\nIn subsequent years the enterprise will make significant contributions toward making LA the best place to Create, Learn, Connect, Live and Play.  The LAWF will have impacts on the metrics, as follows:  \r\n1.\tA source of inspiration for students to pursue creative careers; \r\n2.\tAffordable and safe homes, neighborhoods and playgrounds;\r\n3.\tGreater cultural exchange with other parts of the World;\r\n4.\tAttract many start-up and existing creative industries. \r\n5.\tSupport growth of arts oriented businesses and manufacturers; \r\n6.\tEncourage and exhibit innovation and associated patents;  \r\n7.\tNumerous venture capital investment opportunities; \r\n8.\tHave a profound impact on global culture and economy through worldwide collaborations; \r\n9.\tServe as a spring board for health education and awareness by featuring advances in healthcare, mental wellness, spiritual healing, and healthy foods; \r\n10.\tVibrant park and play space accessible to every child for afterschool and vacation enrichment programs."
Please explain how you will evaluate your project.: "During the first year success of the project will be measured using the following three specific metrics:\r\n1.\tCompletion of schematic design and identification of a location for Pavilion Zero, a draft or final strategic plan for implementing the LAWF, and enlisting the participation of LA Metro in coordinating the development of new transit facilities with the development of fairgrounds.\r\n2.\tNumber of individuals and organizations volunteering to participate and support the promotion, development and operation of the LAWF beginning during the grant period.  1000 or more entities enlisted will be considered a “success.”  \r\n3.\tNumber of public meetings and events in which our collaborators participate, and the number of people attending and informed at those activities.  Staging of 10 or more events involving attendance of 1000 people or more will be considered a “success.”\r\n"
What two lessons have informed your solution or project?: "1.\tA world’s fairs is a large public fair of international scope and reach, typically staged over a period of time ranging up to six months.  A world’s fair is often staged as a means of stimulating the growth and development of international trade, commerce, science, education, art, culture and tourism in a region which offers distinctive themes of general or special benefit to the world.  The vision of the LAWF will act as a catalyst for meaningful and lasting change throughout this region and beyond by generating extraordinary economic growth and opportunity and integrating public transit into the fabric of the City.  Thus the proposed theme for the LAWF is “The Connected City.” \r\n2.\tThe economy of the region signal why the time is right for the LAWF. Greater Los Angeles has $575 billion a year economy, expected to grow by 50% in the next ten years; a consumer market of 18.1 million people; a labor force of more than 4.9 million; 14 leading trade industry clusters creating 2.3 million jobs; the 19th largest economy in the world;  100 consulates and an international community which speaks over 140 languages, making it one of the most ethnically and culturally diverse populations in the world;  121 universities, colleges and educational institutions, including world-class research universities.  It is the creative capital of the World hosting such industries as Performing Arts, Architectural and Interior Design, Entertainment, Motion Pictures, Music, Toys, Automotive Design, Information and Communications Design and Programming, Fashion, Multi and Digital Media, Furniture Design, Biotechnology, Sustainable Technologies and Advanced Medicine, to name just a few.  It is the premier gateway for trade from the Pacific Rim, Canada, Mexico and Latin America to the lucrative consumer market in the United States of America.  It’s two ports handle $380 billion in exports and imports.  Five airports in the region carry over 84 million passengers, and have an economic impact of over $20 billion on the local economy.  Public investment in the County includes $30 billion in rail and bus transportation; $4 billion in airport modernization and $2 billion in Port modernization.  These infrastructure improvements will better connect international visitors enabling regional rail, bus and highway transportation to better serve local communities.  The LAWF will weave these resources into a paradigm for a bright future for the region, the Nation and the world.\r\n\r\n"
Explain how implementing your project within the next twelve months is an achievable goal.: "The LAWF is expected to be implemented over the next TEN YEARS.  The effort was begun with a “Start-up” phase in 2013 during which initial planning and strategy were formulated, monthly outreach meetings were scheduled, and flex teams began to be formed.  In 2014-2015, the grant year LAWF is engaged in the “Exploratory” phase, aimed at completing the the development of the strategic plan, the blueprint for Pavilion Zero, raising initial funds, developing criteria, standards and procedures for subsequent phases, and community outreach for membership, participation and sponsorship.  Achieving the latter goals will enable the subsequent “Launch” phase between 2016 and 2022, when the LAWF will be engaged in aggressive sales, obtaining sponsorship, negotiating and entering into purchase, joint ventures and development agreements  for acquisition, design and development of fairgrounds around the region, and overseeing the completion of venues and ancillary facilities of the LAWF.  Between 2022 and 2024 the project will enter the “Operation” phase, during which LAWF FPC will oversee the operation of the LAWF for two years and possibly beyond.\r\n \r\nDuring the current Exploratory phase, the project team has already begun the process of drafting the strategic plan, identifying and establishing resource contacts in the community to achieve the enterprise objectives.  Some members of the team have been working for a year or more on this enterprise.  Research on other world’s fairs has been done, a theme has been selected, flex teams have been formed, preliminary plans, schedules and budgets have been drawn.  Team members have the experience, strength and confidence that these objectives can be reached and exceeded within the next year.  This grant will insure that the job is done effectively and with the proper level of commitment of time and effort to successfully achieve this phase of the project. \r\n"
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "1.\tPublic skepticism.  This frequently occurs during the early pre-development stages of a large project, when the vision and plan are still being formulated, funding for the project appears out of reach, and the credibility of the project has not yet been tested.   This challenge will be overcome by:  Assembling a team of highly qualified and experienced professionals capable of organizing and managing all stages of project implementation; attracting leaders in business, finance, government, development, trade and culture both within and outside the community and convincing them to participate; formulating a theme, concept and vision which is expansive and inclusive of all segments of the community; informing and promoting support both in and outside the community, particularly internationally.\r\n\r\n2.\tAttracting sufficient funding to jumpstart implementation.  Funding obtained from the grant $100,000 will be to leverage to reach or come close to reaching the goals of the Launch phase, including real estate feasibility studies, preliminary designs, and executing necessary joint power and development agreements, acquiring property, sponsors, developers and operators, and development of fairgrounds and ancillary facilities. \r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - 'Infrastructure (building/space/vehicles, etc.)'
  - Education/training
  - 'Technical infrastructure (computers, etc.)'
  - Community outreach
  - Quality improvement research
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/los-angeles-worlds-fair-collaboration-2014-2015/maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F21921%252Fdisplay%252FScreen_Shot_2014-07-31_at_9.17.55_AM.png=c570x385.png
maker_image_id: '21921'
maker_image_file_name: Screen_Shot_2014-07-31_at_9.17.55_AM.png

---
