---
published: true
organization_id: '2015161'
year_submitted: 2014
category: live
body_class: lime
project_id: '4102034'
title: 'Prototypes: Integrated Health Care for Women and Their Children'
project_summary: >-
  The Pomona Women’s Center is a residential treatment program, serving as
  lifeline to women impacted by addiction, mental illness and trauma.
project_image: 'https://img.youtube.com/vi/6AUZY8VvXXQ/maxresdefault.jpg'
project_video: 'https://www.youtube.com/embed/6AUZY8VvXXQ'
project_areas:
  - SGV
Please identify any partners or collaborators who will work with you on this project.: "Over the years, Prototypes has developed a deep network of government and social services that help us meet the needs of our clients. This includes Los Angeles County agencies such as the Department of Mental Health and Department of Children and Family Services that provide referrals and resources to serve clients. We also collaborate with the criminal justice system including the Public Defender’s Office, California Department of Corrections and County Probation Department to ensure we can serve those who are incarcerated. Partnerships with local entities such as Pomona Unified School District and the Pomona Housing Authority ensure education and housing resources. We also work with East Valley Community Health Centers to provide medical care.\r\n\r\nThese partnerships are long-standing and contribute to the success of our residential program. Three critical factors that have help ensure our successful collaboration is open communication on project status through reports and meetings, effective partnership agreements and mutual support on projects. \r\n"
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  Prototypes is a lifeline to women who are struggling with addiction and other
  serious issues such as domestic violence and mental illness. 
Does your project impact Los Angeles County?: 'No'
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - San Gabriel Valley
  - San Fernando Valley
  - South Bay
  - Westside
What is your idea/project in more detail?: "Prototypes’ Pomona Women’s Center is a unique, integrated and comprehensive residential treatment program for women and their children impacted by mental illness, addiction and trauma. Keeping mothers and children together ensures they both get the help they need.\r\n\r\nAddiction doesn’t exist in a vacuum. Women battling substance use disorders frequently face other serious issues: mental illness, domestic violence, chronic disease, and homelessness. Many are also mothers, a role they are often forced to give up to receive treatment. \r\n\r\nOur Pomona Women’s Center is a leader in integrated health care, addressing all of a woman’s needs- physical, emotional, social, relationship, financial, and more – that must all be treated to ensure success. "
What will you do to implement this idea/project?: "Prototypes’ Pomona Women’s Center has been in operation since 1988, providing residential treatment to women and their children. Our LA2050 project will further the capacity of our Pomona Women’s Center to provide fully integrated healthcare to help women and their families create a foundation for a healthy, independent and successful future. Specifically, it will add critical staff that will help families with their health care needs during and after treatment, focuses on building women’s self-sufficiency to make sure homelessness is no longer an inevitable fate and bolsters our mental health services. \r\n\r\nOur project will add a Health Care Navigator to the team providing case management to families and ensuring that all of their health needs are met. This includes enrolling in health insurance, ensuring that mothers and children receive comprehensive assessments, identifying any resources in the community and following up to make sure treatment and care is being received and moving families toward their goal of self-sufficiency. In addition, this project will support a Vocational Counselor to provide women with the opportunities to gain skills to search and apply for employment. Opportunities and resources are provided on-site to build each client’s resume, ensuring gainful employment once they complete treatment. The project will also help to fund a Mental Health Clinician to provide mental health assessments to women and children. This position will also provide individual, group and family therapy. And finally, the project will also include a vehicle lease for a van that will ensure that transportation is not an issue in accessing care such as bringing a client’s family to the facility for therapy and assisting women and children with doctor’s appointments."
How will your idea/project help make LA the healthiest place to LIVE today? In 2050?: "Among the 18.9 million adults with a substance use disorder in the past year, almost half had a co-occurring mental illness. However, only 7.4% of individuals receive treatment for both conditions and 55.8% receive no treatment at all. Due to the Affordable Care Act, 640,000 people in Los Angeles County are estimated to be eligible for Medi-Cal and 10% of them will need treatment for substance use disorders. This impacts Los Angeles as untreated addiction and mental illness can lead to unemployment, incarceration, child abuse or neglect, homelessness and a cycle of poverty for many families.\r\n\r\nWe can change that. Prototypes’ residential treatment is often the last hope for women with such complex issues because they have nowhere else to go. Through partnerships with local medical providers, social services agencies and the justice system, we remove barriers to access with a “whatever it takes” approach to ensure women receive addiction and mental health treatment. \r\n\r\nResearch has shown that women with substance use disorders also have high rates posttraumatic stress disorder; not surprising then is that more than 87% of the women in Prototypes’ residential treatment have been victims of sexual and/or physical abuse as well as domestic violence. Trauma is then a key focus as staff help clients understand the underlying causes of their addiction and provides them tools to successfully get through difficult situations without the use of drugs and alcohol. \r\n\r\nFurthermore, over two-thirds of women with co-occurring mental health and substance use disorders are mothers, yet most programs do not support a woman’s role as a mother or will not accommodate pregnant and postpartum women. We encourage women to bring their children with them, so they don’t have to choose between their health and their children. Keeping families together not only improves a mother’s success in her recovery, but also impacts future generations in Los Angeles.\r\n\r\nPrototypes’ residential treatment aims to fill the gap in service delivery by taking a holistic viewpoint on health and identifying everything from therapy to housing as necessary treatment for our most vulnerable. Not only to help families get access to healthcare, but we also provided the tools and resources to women become self-sufficient through housing, employment, parenting and education. The program also impacts a second generation who receive care and support to prevent future adverse experiences for children. "
Whom will your project benefit?: "Hundreds of women- those with children, those without, those who are expecting and those who have recently given birth- are brought down by addiction and its myriad challenges. Their issues are often so complex; they have nowhere else to go since many traditional programs may only offer one type of treatment. \r\n\r\nPrototypes’ Pomona Women’s Center will benefit low-income women and their children in Los Angeles County who face barriers in accessing vital behavioral treatment. We also include a client’s family in their recovery progress, providing family therapy and support. \r\n\r\nBased on our services over the years, the project is estimated to serve a client population that consists of the following:  43% Latina/o, 28% white, 27% African-American, 1% Asian/Pacific Islander and 1% American Indian. The project will serve women who struggle with the disease of addiction and may also be victims of domestic violence, have mental illness, be homeless and/or involved with the criminal justice system. They often face difficulties such as poverty due to insufficient skills and employment, language barriers, lack of access to public benefits and/or may have lost custody of their children. "
How will your project impact the LA2050 “Live” metrics?:
  - Healthcare access
  - Number of households below the self-sufficiency standard
  - Rates of homelessness
  - Rates of mental illnesses
  - Prevalence of adverse childhood experience (Dream Metric)
  - Percentage of LA communities that are resilient (Dream Metric)
  - >-
    Percentage of residents receiving coordinated healthcare services (Dream
    Metric)
Please elaborate on how your project will impact the above metrics.: "• Number of households below the self-sufficiency standard: Prototypes provides comprehensive support services that set families up for success when they leave. This includes vocational training, employment support, and educational classes a to ensure women have their GED, can gain work experience and pursue higher education. In addition, women are provided life-skills that such as budgeting and nutrition to prepare them to create a stable household. Staff also help clients secure any public benefits and resources.\r\n• Rates of homelessness: First, Prototypes’ residential facility allows women to bring their children with them to live on campus in dorms with a length of stay ranging from 3 months to much longer depending on their treatment needs. Prototypes then works with partners in the community to find housing for families once they leave our residential facility. Prototypes also operates a 32-unit affordable housing complex for families who were homeless before accessing treatment. \r\n• Healthcare access and percentage of residents receiving coordinated healthcare services: Prototypes works with our community partners to identify individuals in need of treatment, including medical providers, to obtain mental health or other referrals. Our staff then works with families to assess their health needs and create an integrated treatment plan. We also assist families in obtaining health insurance or, more likely, help them sign up under Medi-Cal if they meet those requirements. Counselors and case managers work closely with other providers to make sure that care is coordinated and open communication exists.\r\n• Rates of mental illnesses: All women and children who come to the Pomona Women’s Center are assessed for mental health needs. Appropriate prevention and treatment is provided to ensure that both receive the care they need.  \r\n• Percentage of LA communities that are resilient: Prototypes’ comprehensive services help rebuild lives devastated by complex health issues. The treatment, skills and resources allow families to successfully reintegrate into their community. By addressing all of their needs, Prototypes indirectly impacts communities where the mothers and their children reside.\r\n• Prevalence of adverse childhood experience: By keeping mother and child together, Prototypes encourages parent-child bonding. Mothers receive parenting skills and learn about child development to better support their child’s growth. "
Please explain how you will evaluate your project.: "Prototypes routinely measures success related to program effectiveness, accessibility, efficiency and access. Data from employee survey results, client satisfaction surveys, stakeholder feedback, financial reports and program outcomes are reviewed by senior leadership and the Board of Directors to inform strategic goals each year. Prototypes monitors objectives and outcomes through staff records of client data, clinician observation and client self-assessment through surveys. Prototypes is also in the process of implementing an electronic health record system that will enable automatic tracking of aggregated outcomes, providing Prototypes’ leadership and Board of Directors with real-time outcome data to evaluate program effectiveness. \r\n\r\n1. Decrease adult drug use, trauma symptoms and adult risk factors\r\n2. Decrease child trauma symptoms and child risk factors\r\n3. Increase a family’s well-being through employment, housing and health care access\r\n"
What two lessons have informed your solution or project?: "First, Prototypes has helped more than 100,000 individuals lead healthy and productive lives since 1986. This extensive experience has allowed Prototypes to refine our service model to best help the communities we serve. As the issues and population changes over time, Prototypes deep connections within the areas we serve helps stay abreast of changes to meet the needs of our clients. This has led to increasingly integrated services and a program that is intense in order to help our clients become self-sufficient. Currently, healthcare reform has changed how people access care and demands that medical and behavioral health care become integrated. That is why we have identified a need for a Health Care Navigator to assist families with everything from insurance to meeting doctor’s appointments.\r\n\r\nIn addition, there will be more individuals able to access services over the course of the year due to health care reform. Increasing our staff capacity will help to ensure we can meet the demand and still provide high-quality services that set up families for successes once they leave Prototypes. "
Explain how implementing your project within the next twelve months is an achievable goal.: >-
  Prototypes has operated the Pomona Women’s Center since 1988 and the program
  is currently fully operational. Our LA 2050 project will enhance this current
  program and the project aspects are easily undertaken within a 12-month
  period. In addition, Prototypes has extensive experience with short start-up
  timeframes for grants and has the capacity to recruit, hire and train
  necessary staff as well as procure a vehicle lease. 
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "The Affordable Care Act (ACA), or health care reform, remains the single most important event that will impact Prototypes over the course of this next year. It will benefit the communities we serve by increasing access to insurance for individuals seeking substance use and mental health treatment, as these services are now essential health benefits under the ACA. Access to preventive care, coverage for pre-existing conditions for families, and required coverage for pregnant and postpartum women will also directly benefit Prototypes’ clients in a positive way. Health care reform also presents many uncertainties in public funding and policies. At both the State and County levels, there are many unknowns as the reforms are implemented this year, making it extremely difficult in developing a long-term strategy for funding. We work closely with our government funders to stay abreast of the latest developments and to ensure our voice is heard.  \r\n\r\nIn addition, attracting the highest quality staff has become difficult as organizations compete for professionals in the behavioral health arena. As part of our current strategic plan, Prototypes’ administrative team has implemented new recruiting and on-boarding methods for employees to ensure dynamic staff team. This has included an employee referral program and other marketing efforts to the behavioral health field. Prototypes is also focused on presenting our treatment model and research at conferences over the course of the next year. This will help to position Prototypes has a premiere leader in the field and bolster our reputation in providing innovative, high-quality treatment which will attract prospective employees. \r\n"
What resources does your project need?:
  - Money (financial capital)
  - Publicity/awareness (social capital)
  - 'Infrastructure (building/space/vehicles, etc.)'
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/prototypes-integrated-health-care-for-women-and-their-children/img.youtube.com/vi/6AUZY8VvXXQ/maxresdefault.jpg
youtube_video_identifier: 6AUZY8VvXXQ

---
