---
published: true
organization_id: '2014194'
year_submitted: 2014
category: learn
body_class: blueberry
project_id: '4102202'
title: Strivers.LA - digital tools for student success
project_summary: >-
  Strivers.LA is a free digital tool that helps students succeed- we get bosses,
  family & friends to support students' educational goals.
project_image: 'https://img.youtube.com/vi/lz8FDz2KN0s/hqdefault.jpg'
project_video: 'https://www.youtube.com/embed/lz8FDz2KN0s'
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - SGV
  - SFV
  - SOUTH BAY
  - WESTSIDE
Please identify any partners or collaborators who will work with you on this project.: "STRIVERS.LA is being incubated by New Economy Campaigns, a digital strategy consultancy that has created national and global programs to leverage technology for social impact. Creating accessible ways to engage with causes that matter is the cornerstone of New Economy Campaigns’ work.  The New Economy Strivers team includes a digital strategist, a designer/ developer, a project manager, an educator whose experiences teaching inspired the project, and a community manager. Collectively, we bring more than 75 years of experience to building Strivers. Our team is made up of \"strivers\" and we believe in educational access for all. \r\n\r\nStrivers.LA is partnering with Los Angeles City College Foundation for implementation of our app and outreach to students.  LACCF is a 501(c)(3) corporation established in 1968 to increase the educational opportunities for students of LACC. The Foundation creates and promotes new initiatives to meet unfunded programmatic needs of the school community. LACCF will ensure access to LACC students during product development, pilot, and implementation phases, as well as assist with program evaluation.\r\n\r\nLos Angeles City College serves approximately 18,000 students annually, and they have one of the most diverse, and most economically challenged student bodies in California.  LACCF is confirmed as a partner and participated in the development of this application, and will receive a portion of the grant funds if we are successful, in order to support on-campus outreach. LACCF provides us with direct, on-campus access to students, and will act as a liaison with the College overall and with the broader Los Angeles Community College District.\r\n\r\nIf our partnership with LACCF is successful, we hope to expand this partnership throughout the Los Angeles Community College District, which serves more than 250,000 students annually.\r\n\r\nNew Economy Campaigns has consulted for LACCF on digital outreach and engagement strategies, and we have developed a strong working relationship.  \r\n\r\nThe three elements essential for the success of this partnership are:\r\n●\tReciprocal benefit for each partner; Strivers.LA will have access to a student population that’s perfect for our application, and LACCF will have access to a digital tool that will help its students succeed.\r\n●\tCommon goals:  wanting to help struggling students succeed and complete a degree or certificate program, or successfully transfer to a four-year institution.\r\n●\tClear expectations and communication.\r\n"
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  Strivers.LA is a free digital tool that helps students succeed- we get bosses,
  family & friends to support students' educational goals.
Does your project impact Los Angeles County?: 'No'
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - San Gabriel Valley
  - San Fernando Valley
  - South Bay
  - Westside
What is your idea/project in more detail?: "Strivers.LA is an application designed to help students succeed.  Our current product is a free digital exam and study optimization tool. When a student signs up for Strivers.LA and enters an exam date, the application generates suggested study times and sends messages to keep the student’s studying on track. Strivers.LA exam calendars are designed to be easily sharable so students can tell their social networks and their employers about their study needs.\r\n\r\nMany of LA's college and high school students work part-time and even full-time during the school year. Add in time for family, friends, and a romance, and time management can really suffer. Strivers.LA seeks to help Los Angeles students succeed, one exam at a time.  \r\n"
What will you do to implement this idea/project?: "With Strivers.LA, students are prompted to share their exam calendars with people who can support their academic success (employers, parents, romantic partners, or roommates). Strivers.LA gives students time management tools and involves their social networks and employers in their education. \r\n\r\nNew Economy Campaigns and the Strivers.LA team have already built a working beta version of the Strivers.LA application, which is the first step to creating the kind of comprehensive application students need.  We'd like to reach more students in order to get the needed feedback to improve the application. \r\n\r\nFunds from the 2014 LA2050 grant would be used to support:\r\n●\tDeveloping a revised version of the application in early 2015 based on student feedback from testing during summer and fall 2014.\r\n●\tPlanning and developing new components of the application to facilitate participation, increase automation, and expand scalability.\r\n●\tDeveloping a method for gamifying student participation, creating class vs. class and school vs. school metrics.\r\n●\tRecruiting students to use the app (incentives) and funding community manager support (staff time)\r\n●\tSupporting the Los Angeles City College Foundation in providing incentives and outreach to current LACC students.\r\n●\tPartnership outreach to local businesses to seek ongoing sponsorship and marketing incentives to students.\r\n●\tPlanning and implementing a comprehensive evaluation strategy.\r\n\r\nWe will recruit students to use the Strivers.LA app through:\r\n●\tOnline outreach via Facebook, twitter, and Instagram, using a content-driven strategy to engage students with fun and useful content about school success (and dealing with exams).\r\n●\tIn-person outreach through Los Angeles City College Foundation, student organizations, and nonprofits.\r\n●\tRecruitment incentives for students to reach out to their peers and refer them to Strivers.LA.  \r\n\r\nWe aim to  create a culture of focus on exams, planning ahead for studying, and increasing student engagement generally on community college campuses in LA, improving education outcomes and increasing graduation rates.\r\n"
How will your idea/project help make LA the best place to LEARN today? In 2050?: "Currently, California is one of the toughest places to be a community college student in the country.  Our college completion rates are far below the national average, and our students arrive from high school without good study habits; they often require remedial classes before they can begin college-level work.  Strivers.LA can help students today improve their study habits and increase their likelihood of completing a degree or certificate. Young people (as well as older students) who are balancing part- or full-time work with studies and family obligations understandably have a tough time.\r\n\r\nSecuring a college degree is central to a student having an increased standard of living throughout his or her life. Some studies show a lifetime differential of more than $1M between those completing a four-year degree and those who do not.  Increased graduation rates result in better outcomes for the community overall.  \r\n\r\nOver the long term, Strivers.LA will help to create a culture of academic success and responsibility within our community college system and in the LA region overall, by recognizing the students who are working hard to succeed, as well as the employers and educators who are supporting them.  We’ll give local businesses a way to recognize and reward students who are making an extra effort (and potentially find future employees through our network someday).  We’ll give local leaders a way to see which businesses and campuses are stepping up to support students. \r\n\r\nWe’ll celebrate all of LA’s Strivers as they learn and succeed.\r\n\r\nIn 2050, if our initiative is successful, our community college system will have educated tens of thousands of better-prepared, employed and employable students, ready to work in growth industries that will power the LA economy for the subsequent 50 years; healthcare, technology, hospitality and tourism. We’ll demonstrate success by increasing the percentage of students who successfully complete college; we’ll improve profitability for businesses by reducing personnel and retraining costs, encouraging increased hiring and local investment.  Most importantly, we’ll have created deep relationships between our community college system and local employers, developing a collaboration that understands that supporting student workers will result in an improved economic environment for the entire community.\r\n"
Whom will your project benefit?: "Our Strivers.LA app is designed for low-income, working community college students, but any high school or college student can benefit from its reminders to study, prompts to share their academic calendar with friends, family, and employers, and motivational study messages.  Our app will benefit anyone who is seeking to better their life and employment prospects through education – it can be used freely by anyone who signs up to participate.\r\n\r\nNationally, 74% of students worked during the academic year, and 15 % are working full-time.  Juggling work and school schedules leads to skipped classes, inadequate sleep, and even no-show exams. Research shows that every extra hour a student works above 10 hours/week lowers GPA by a measurable amount.  Sixty percent of community college students work more than 20 hours per week and 25% work more than 35 hours per week.  Among 18 countries tracked by the OECD, the United States finished last (46 percent) for the percentage of students who completed college once they started it.  In California, fewer than 28% of students who begin a two-year college program complete a degree within six years; for those studying part time, this percentage falls to less than 12%, in both cases significantly below the national average.  Los Angeles must improve its college completion rates in order to reach its economic potential.  \r\n\r\nThrough our partnership with Los Angeles City College Foundation, we’ll be focusing our work on engaging LACC students.  LACC's student population is among the most diverse in the nation. Of the College’s more than 18,000 students, 54% are immigrants to the United States and 45% are first-generation college students. Current LACC students are low-income, with 70% receiving a Board of Governors waiver for tuition and 53% receiving some form of financial aid. A number of students are even homeless and hungry. Through our partnership with LACCF, we will be able to engage directly with this population, helping to bolster the employment that most students use to support their educational goals and improving their likelihood of completing an associate’s degree or transferring to a four-year school.\r\n"
How will your project impact the LA2050 “Learn” metrics?:
  - >-
    Percentage of community college students completing a certificate, degree,
    or transfer-related program in six years
Please elaborate on how your project will impact the above metrics.: "Strivers.LA is designed to increase college completion and graduation rates by improving study habits, time management and student performance on exams.  We're seeking to create a culture of academic success by involving students' friends, family, and employers in their education. Getting many students at an institution using Strivers is designed to change the social norms for study, test prep, and achievement for an entire institution.\r\n\r\nStrivers.LA seeks to solve the problem of students’ poor time management and the difficulty of balancing work and school. Students need time off from work and a plan for studying.  Strivers.LA sends messages to students in advance of their exams with reminders and study tips, and gives students tools to negotiate time off.\r\n\r\nFuture versions of the application will allow employers, family members, and friends to sign on to support students, and a student report-back and incentive process, and will expand to provide support in Spanish and other languages.\r\n\r\nStrivers.LA has just launched its first working beta application, and is in the process of recruiting test users (students taking classes during the 2014 summer session at Los Angeles City College and Santa Monica College).\r\n"
Please explain how you will evaluate your project.: "Strivers.LA has built-in metrics so that we can understand whether students are using our app, and interacting with our content.  Our success metrics for the application will include:\r\n●\tNumber of new users/ signups.\r\n●\tNumber of students entering an exam date.\r\n●\tNumber of students completing a post-exam report-back survey.\r\n●\tReported impact of the app on that survey.\r\n●\tNumber of users returning to use the app for future semesters/ exam dates.\r\n\r\nOutside of the Strivers.LA application metrics themselves, we’ll work with Los Angeles City College Foundation to attempt to track longer-term impact, including:\r\n●\tNumber of students using Strivers.LA who successfully passed their classes.\r\n●\tNumber of students using Strivers.LA who complete a degree or certificate program or transfer.\r\n●\tDifferences between students using Strivers.LA and those who don’t.\r\n\r\nEventually, we’d love to create a true (randomized controlled trial evaluation) of the Strivers.LA application.\r\n\r\n"
What two lessons have informed your solution or project?: "The Strivers team draws inspiration from many academic disciplines and types of research. \r\n\r\nPublic health research shows that positive habits can be contagious, and that friends and family influence can help support positive behavior change. Extrapolating these health results to educational achievement, the Strivers team set out to build a product that would allow students to get their social networks on board with their academic success. \r\n\r\nPolitical science research shows that \"Helping people to make plans can increase their likelihood of following through on intentions\" so Strivers prompts students to plan to study. Voter turnout rates can be significantly increased through text message reminders so we incorporated text message exam reminders. \r\n"
Explain how implementing your project within the next twelve months is an achievable goal.: "We have already developed a beta version of the Strivers.LA application, and the focus of this proposal and grant would be to improve our existing product to make is as appealing to students as easy and fun to use as possible.\r\n\r\nWe are seeking quick adoption by as broad a user base as possible among low-income community college students in Los Angeles, and then adapting and improving the software based on community and student response.  Given that the software is already ready to use, implementing the next phase of the Strivers project over the next year is feasible, especially with the participation of Los Angeles City College Foundation as a partner.\r\n"
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "Two major challenges to the success of our app are getting students who are already overwhelmed with multiple responsibilities to sign up and continue to participate/ use the app, and the challenges of working with the extremely large and complex Los Angeles Community College District.\r\n\r\nOur strategies for recruiting and retaining student users include:\r\n●\tSignup and referral incentives.\r\n●\tRecruiting local businesses to provide incentives for success and participation.\r\n●\tDeveloping gamification strategies so students can compete with each other, with other classes and schools to show success and drive recruitment and participation.\r\n●\tDeveloping a positive social network/ social feedback loop among students to support using the app and future success.\r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - Quality improvement research
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/strivers-la-digital-tools-for-student-success/img.youtube.com/vi/lz8FDz2KN0s/hqdefault.jpg
youtube_video_identifier: lz8FDz2KN0s

---
