---
published: true
organization_id: '2014094'
year_submitted: 2014
category: connect
body_class: tangerine
project_id: '4102224'
title: The Mirror Mirror Project
project_summary: >-
  After the face-to-face collaborations, a traveling exhibition will showcase
  the artist and youth artwork side by side in parks all across LA
project_image: 'https://img.youtube.com/vi/awJQoJqGL-o/hqdefault.jpg'
project_video: 'https://www.youtube.com/embed/awJQoJqGL-o'
project_areas:
  - CENTRAL LA
  - EAST LA
  - SOUTH LA
  - SOUTH BAY
  - WESTSIDE
Please identify any partners or collaborators who will work with you on this project.: "1. My Friends Place (http://myfriendsplace.org/) (CONFIRMED)\r\nWe have not worked together before but we have worked with Safe Place for Youth (which is a very similar drop-in center two times before)\r\n\r\nThree Factors:\r\n1. Create detailed timeline of project: That we sit together together as a team and map out all the details of this program together making sure MM Project and My Friend’s Place have a specific plan of the entire project including how many artists will be coming in each day to work, which staff will be coordinating the project and helping pair youth and artists together. \r\n2. The safety of the participants: Both the youth and artists feel taken care of and respected as they create their artwork.\r\n3. Communication between MM Project coordinators and My Friend’s Place directors and staff \r\n\r\n\r\n2. MOCA (Not confirmed but have reached out and hoping to do a mobile exhibit unit for the final closing exhibition (after the exhibit has gone to all the parks) like they did with the Mike Kelley mobile homestead exhibit outside their museum)\r\n\r\nThree Factors:\r\n1. Able to use space outside of MOCA \r\n2. Open communication between MOCA and MM Project on rules of exhibiting outside the museum \r\n3. Will be able to advertise with MOCA of the exhibition \r\n\r\n\r\n3. PARKS of LA (None of these are confirmed yet and are just ideas of different parks around LA and the goal is to bring the exhibition to a broad audience in many different parks) \r\n        -Griffith Park \r\n\t-Grand Park\r\n\t-Exposition Park\r\n\t-Kenneth Hahn State Rec Area\r\n\t-Barnsdall Art Park \r\n\t-Pan Pacific Park Rec Center\r\n\t-Hollenbeck Park\r\n\t-Chesterfield Square Park \r\n\t-Santa Monica\r\n\t-Venice\r\n\r\nThree Factors:\r\n1. The mobile exhibition will be able to find a nice location at each park to create a open air exhibition by opening the truck and creating a community event for a period of 3-4 hours on a specific day\r\n2. The park will allow the event to be advertised on a website\r\n3. The parks will each have a written contract with specific rules so that the exhibit and park are in clear agreement and communication for each event in order to ensure each event is carried out safely \r\n"
Please describe yourself: Collaboration (partners are signed up and ready to hit the ground running!)
'In one sentence, please describe your idea or project.': >-
  After the face-to-face collaborations, a traveling exhibition will showcase
  the artist and youth artwork side by side in parks all across LA
Does your project impact Los Angeles County?: Yes (benefits a region of LA County)
Which area(s) of LA does your project benefit?:
  - Central LA
  - East LA
  - South LA
  - South Bay
  - Westside
What is your idea/project in more detail?: "The Mirror, Mirror Project starts with one simple idea-- to see one another--face to face. Mirror, Mirror sits us directly in front of a homeless epidemic we nearly ignore, and ourselves--so we can take a look at what we have been overlooking. Without the security of our studio walls, Mirror, Mirror welcomes professional artists and homeless youth to sit across from each other and see how creating portraits of the other makes us each the same--human beings. \r\nOnce the pairs are finished with their portrait, each portrait is displayed side by side in a traveling art installation in parks all across LA where the community is invited to connect with the work, the artists and the youth. \r\n\r\n"
What will you do to implement this idea/project?: "1. Invite Artists: First, invitations to professional artists working in any/all mediums in Los Angeles will be asked to participate to work with a youth of My Friend’s Place (the goal is to get about 80-100 different artists signed up). Once signed up, the artists will get a livescan (background check) done before coming into the center to work with the youth. \r\n\r\n2. Hold Information Meeting(s): An artist kickoff event will be held at a specific location to give the artists a chance to get their livescans done and to get all the details for participating in the project. \r\n\r\n3. Create Art: The artists can provide art materials as they wish to share with their partners or select from the materials we have provided. They will collaborate with their partner to create their portrait and have their portrait created by their partner. Once the artists have their livescans complete (and they have cleared) the artists will be able to pick a day they would like to come into the drop in center during the 3-4 month art making period. (We will create a sign- up sheet for the artists to pick from specific days and times so there are not more than 6 artists coming into the center at one time).\r\nAs the artists sign up and start coming into the center, myself and another lead artist will help make sure the artists and youth are getting paired up together and have a space to work together on their portraits. \r\n\r\n4. Frame the Work: The artists and youth will be able to work together until they finish their portraits. Once each partnership finishes a portrait, we will take them to get framed.  \r\n\r\n5. Install the work and hold exhibitions: The portraits will be displayed for the community to interact with in exhibitions around LA. The artwork will be to stored on a mobile truck to be able to transport to different parks across LA. At each park we will have open-air exhibitions with mobile display walls to set up at each location.\r\n"
How will your idea/project help make LA the best place to CONNECT today? In 2050?: "TODAY: This project helps make LA the best place to connect today because it gives people a space for real interaction between two communities that normally don't connect with one another. The outcome is that each partner sees something they never saw in themselves which consequently gets projected not only in their portraits but in their perspectives forever. As this project continues into the future, greater compassion between the people in our community will be present. This project acts as a portal to ourselves, to others, and our society as we connect across social boundaries. This project allows us to powerfully share the magic of the artistic process and positively influence the youth to see their own dreams and empower them to purse something that inspires them and even seek help to get out of their current situations. The artists see what they have been blind to and are able to form new perspectives and get past judgments they have on the homeless.\r\n\r\n2050: People will be able to have a changed perspective of what homelessness looks like. They will feel more empathy towards people that don’t have a home and be able to connect on a new level. In 2050 more people will want to volunteer at drop-in centers, provide services for drop-in centers, bring food, materials, and come up with better ideas to help young people without a home. Because this project allows us to see what the homeless need on a deeper level, we can see where we are still lacking shelter, clothing, food, access to wifi, transportation, and employment opportunities.  \r\n"
Whom will your project benefit?: "1. At-Risk Youth\r\nFirst the project will benefit the youth of My Friend’s Place. Not only will the youth get a one-on-one mentorship but they will feel heard and seen on an individual level. They will have a chance to share a story and passion through a form of art that excites them and get the support they may be wanting to express an idea with guidance. \r\n\r\n2. Artists\r\nThe artists will benefit greatly through this project as they will be forced to step outside their comfort zones of their studios to create art. They will have a space to let their walls down, be vulnerable themselves and share stories with youth they may haven’t shared with anyone else. The artists will open themselves up to a new perspective on what it means to be without a home and actually put themselves in their partner’s shoes. They will be forced to work on a new level, have the chance to be a teacher and a student at the same time. They will find themselves having a much bigger connection to their partner than they initially thought and open up a whole new level of seeing people for who they are instead of making judgments from an outside appearance. \r\n\r\n3. The Community\r\nAs the exhibition gets to travel around the LA parks, our whole community gets to experience the relationships that were formed through this project. The youth, artists, and the community in each park will be invited to experience the portraits and the stories of the relationships that formed and get to know others they may have never had the chance to meet before. \r\n\r\n4. Community parks\r\nThe parks around LA will benefit as this will open up excitement and activity. This project will show the community that the parks are always there to enjoy the beautiful city of LA and the community that we are.\r\n\r\n5. My Friend’s Place \r\nThis will benefit My Friend’s Place drop-in center in a way that will reinforce their model of being a low barrier service structure using their harm reduction approach. By bringing the MM Project to this drop-in center it will provide education and support and equip the youth to reduce the harmful effects associated with high risk street\r\nsurvival behavior and minimize the psychological, physical, and social barriers that typically deter youth from seeking and accepting assistance from a social service agency.\r\n"
How will your project impact the LA2050 “Connect” metrics?:
  - Rates of volunteerism
  - Voting rates by race
  - Adults getting sufficient social & emotional support
  - Attendance at cultural events
  - Participation in neighborhood councils
  - Percentage of Angelenos that volunteer informally (Dream Metric)
  - Government responsiveness to residents’ needs (Dream Metric)
  - Attendance at public/open street gatherings (Dream Metric)
  - Residential segregation (Dream Metric)
  - Access to free wifi (Dream Metric)
Please elaborate on how your project will impact the above metrics.: "1. Rates of volunteerism & % of Angelenos that volunteer informally \r\nMMProject relies on the artists to volunteer their time to work with a youth. Each time this project gets implemented, more people will find out they too can volunteer to be an artist and work with the youth. Not only will artists want to volunteer but once the exhibition gets showcased, the community will find out they can volunteer a number of ways with the homeless (providing other services, donating food, outreach, volunteering at homeless shelters all around LA, etc). \r\n2. Voting rates by race\r\nBecause My Friend’s Place serves a large population of different races, the unique setup of bringing in artists as mentors one-on-one with the youth provides the space for intimate and meaningful conversation. During these conversations artists can actually encourage the youth to really voice their opinions. \r\n3. Adults getting sufficient social & emotional support\r\nThe MMProject brings a great deal of social and emotional support each time the artist/youth partnership sits down across from each other to do their portraits. They get the space to really connect and open up about topics they normally would be afraid to share. \r\n4. Attendance at cultural events\r\nWill provide a space for new communities to meet each other and share stories and find their common interests. By having the MM Project exhibit in a traveling form, each exhibit will be its own cultural event and will naturally build a larger audience to attend. \r\n5. Participation in neighborhood councils\r\nBecause face-to-face interaction and in person mentorship build the strongest trust and belief in someone, more of the youth and artists are able to gain confidence in their voice and see how important each of their opinions matter in this city.\r\n7. Govnt responsiveness to residents’ needs\r\nNot only do the artists coming into the homeless drop in center learn the needs of the homeless at-risk youth, they are able to communicate that to our community and then to the government. \r\n8. Attendance at public/open street gatherings\r\nBringing the exhibition to the people in the parks with the traveling art show will get people out.\r\n9. Residential segregation\r\nThe process of this project connects two different social classes together that share the same community. \r\n11. Access to free wifi\r\nWe learn firsthand of where we lack free wifi w/ the homeless youth as they have laptops/iphones & need internet on the street to get help, food, a job or clean clothes"
Please explain how you will evaluate your project.: "1. We will evaluate the project based on the number of youth that participate with an artist and create their portrait. Also on the number of volunteered artists that come in to work with the youth.\r\n2. We will evaluate the project based on the attendance at public park exhibitions.\r\n3. The percentage of Angelenos that volunteer to put the events on in the public. \r\n4. The percentage of adults getting sufficient social and emotional support\r\n5. The government responsiveness to residents' needs and residential segregation "
What two lessons have informed your solution or project?: "Lesson 1 Youth will continue to live on the streets if no one is there to guide or mentor them. Someone to motivate a young person that they CAN achieve a goal is important. Having a one on one interaction where the youth actually get seen as a person instead of put into the dehumanizing category “homeless”. \r\n\r\nLesson 2 Our community will continue to ignore homelessness and label them and not provide enough. (Examples: the need for housing for homeless, Skid Row, not enough services/shelters for homeless)\r\n"
Explain how implementing your project within the next twelve months is an achievable goal.: >-
  Having implemented this project two times in the last year (with a very small
  budget) we exceeded our goals for the first and second show in the amount of
  participation and the work created. I know implementing it in the next 12
  months is beyond achievable with our network of artists here in Los Angeles
  and the excitement around creating art and self expression. With My Friend’s
  Place having the space for the artists to come in to work with the youth, I
  know that a secure space is ready for the creation of the portraits to be
  made. My Friend’s Place also sees about 100 youth a day, many of which, are
  excited to create art already and use art as a form of self expression. 
Please list at least two major barriers/challenges you anticipate. What is your strategy for ensuring a successful implementation?: "One major challenge with this project is having some of the youth stay around long enough to finish their portrait of their partner. To ensure there will be enough portrait pairs to display I have set up to invite many more artists to come in than needs to complete a traveling show. Another strategy for this is to also let the artists know ahead of time that their partner may not come back to work with them a second time and that they may need to partner up with a second youth at the drop-in center. A third action we have in place is to have them try to create their portraits with their partner on the first session or create a collaborative piece together. \r\n\r\nA second major challenge is dealing with the livescans getting cleared in a timely manner since they could take up to 1 month to clear. When we did this project before, the livescans would take 5 days to clear for some artists and almost a month for other artist’s scans to clear. It created a lot of stress and anxiety for the artists because the delayed livescan would then delay them from coming into to work with the youth and then not provide them with enough time to work on their portraits. Our strategy to ensure this works efficiently is to create a different timeline. For example, the artist kickoff will be about 1 month before the artists actually start coming into the center to work so that they have time to get their scans cleared and gather the materials they need to work with their partners. \r\n"
What resources does your project need?:
  - Network/relationship support
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - 'Infrastructure (building/space/vehicles, etc.)'
  - Education/training
  - Community outreach
cached_project_image: >-
  https://archive-assets.la2050.org/images/2014/the-mirror-mirror-project/img.youtube.com/vi/awJQoJqGL-o/hqdefault.jpg
youtube_video_identifier: awJQoJqGL-o

---
