---
published: true
organization_id: '2015004'
year_submitted: 2015
category: play
body_class: strawberry
project_id: '5102009'
title: >-
  Have fun exercise and spend quality time with the family in a safe and clean
  environment
project_summary: >-
  We want to create a place that kids can play and learn all in the same
  environment. Parents can feel confident that their children will exercise and
  have fun while still keeping up with school work. Kids in a society that are
  stuck on technology can come and play and run around like kids used to.
project_image: 'https://img.youtube.com/vi/JrkPrBnN4UI/hqdefault.jpg'
project_video: 'https://www.youtube.com/embed/JrkPrBnN4UI'
Where will you be working?:
  - San Fernando Valley
  - 'Adventure Playhouse 1116 San Fernando Rd. San Fernando, Ca 91340'
How do you plan to use these resources to make change?:
  - Conduct research
  - Engage residents and stakeholders
  - Implement a pilot or new project
  - Expand a pilot or a program
  - Advocate with policymakers and leaders
  - Implement and track policy
  - Build a homework / tutoring center with computers for kids to use for free.
How will your proposal improve the following “Play” metrics?:
  - Access to open space and park facilities
  - Number of children enrolled in afterschool programs
  - Per capita crime rates
  - Percentage of residents that feel safe in their neighborhoods
  - Number (and quality) of informal spaces for play (Dream Metric)
Describe in greater detail how you will make LA the best place to play.: "We have been growing our presence within the community for the last 3 years and have been implementing programs and fundraisers for supporting causes. We understand that schools are in limited supply of funds for staffing and we would like to become an alternative for kids to come and do their homework in a safe environment with helpers and computers to do research and practice any area of subjects with the Khan Academy online. Then once all subjects are completed they would be in a safe and supervised play are with jumpers, slides, obstacle courses and table games to exercise and have fun while de-stressing from a long day of school and studying. \r\nWe would also like to add enrichment classes for toddlers and infants including Mommy & Me, art, and music programs to increase development while playing and developing motor skills. \r\nWe would be providing more services for the community to come and feel safe and have fun while playing together For instance, providing free play times every other weekend to promote health and the importance of spending time with your children. The more the children spend with a child the better they develop both mentally and physically."
Please explain how you will evaluate your work.: >-
  Evaluations will be based on attendance and community involvement. With the
  city wide events and people signing up for information and programs we will
  see where we can grow and where more funds can be allocated if needed.
How can the LA2050 community and other stakeholders help your proposal succeed?:
  - Money (financial capital)
  - Volunteers/staff (human capital)
  - Publicity/awareness (social capital)
  - 'Infrastructure (building/space/vehicles, etc.)'
  - 'Technical infrastructure (computers, etc.)'
  - Community outreach
  - Network/relationship support
cached_project_image: >-
  https://archive-assets.la2050.org/images/2015/have-fun-exercise-and-spend-quality-time-with-the-family-in-a-safe-and-clean-environment/img.youtube.com/vi/JrkPrBnN4UI/hqdefault.jpg
youtube_video_identifier: JrkPrBnN4UI
organization_name: Adventure Playhouse Indoor Activity Center

---
