---
published: true
organization_id: '2015157'
year_submitted: 2015
category: live
body_class: lime
project_id: '5102240'
title: >-
  Vida en equilibrio:Aplicación móvil para el bienestar/Life in Balance: A
  Mobile Wellness Application
project_summary: >-
  To design and implement a mobile chronic disease prevention experience.  This
  app will present original, evidence-based content, and will also include live
  interaction with health educators and other participants throughout the
  duration of the experience.  The experience will be available in English and
  also in Spanish.
project_image: >-
  http://maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F23673%252Fdisplay%252Fvidaenequilibrio.png=c570x385
Where will you be working?:
  - County of Los Angeles
How do you plan to use these resources to make change?:
  - Conduct research
  - Implement a pilot or new project
How will your proposal improve the following “Live” metrics?:
  - Access to healthy food
  - Obesity rates
Please explain how you will evaluate your work.: "The primary evaluation will be conducted with the pilot program prediabetes participants. \_They will take a survey prior to program commencement to test their knowledge of prediabetes and type 2 diabetes. \_This survey will be redone at the end of the one-year period again to see if there are any improvements in their knowledge. \r\n\r\nA lifestyle survey developed by the Minneapolis American Indian Center (Minneapolis American Indian Center, 2004) will be administered at three, six, nine and twelve month intervals to check on the participants’ progress with the mobile DPP program. \r\n\r\nIn addition to the self-reported data, A1C testing will be conducted at baseline and at the same intervals as when the surveys are administered and will be done by staff working at the DPP partners. The A1C testing will determine if the program participants are successfully able to use the mobile DPP platform to reduce their risk."
How can the LA2050 community and other stakeholders help your proposal succeed?:
  - Money (financial capital)
  - Network/relationship support
cached_project_image: >-
  https://archive-assets.la2050.org/images/2015/vida-en-equilibrio-aplicación-móvil-para-el-bienestar-life-in-balance-a-mobile-wellness-application/maker.good.is/s3/maker%252Fattachments%252Fproject_photos%252Fimages%252F23673%252Fdisplay%252Fvidaenequilibrio.png=c570x385.png
maker_image_id: '23673'
maker_image_file_name: vidaenequilibrio.png
organization_name: Polar Tech Ed and Consulting LLC/Patrick Leon

---
